// Auto-generated by update-trends.mjs
// Last updated: 2026-07-11T23:05:12.545Z
// DO NOT EDIT MANUALLY - this file is overwritten every 30 minutes

import { TrendItem } from "@/lib/google-trends";

const today = new Date().toISOString().split("T")[0];

export const preloadedTrends: Record<string, TrendItem[]> = {
  US: [
    {
      title: "luis suarez",
      slug: "us-luis-suarez-2026-07-11",
      traffic: "5000+",
      description: "Harry Kane y Luis Suárez, cara a cara: la foto que compartió el goleador uruguayo",
      source: "Montevideo Portal",
      sourceUrl: "https://www.montevideo.com.uy/Deportes/Harry-Kane-y-Luis-Suarez-cara-a-cara-la-foto-que-compartio-el-goleador-uruguayo-uc967928",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR6zuZVc1d4Y6QqjXghpKuVEo5iG0pY2UxheoDufbipzFy0_78Yvv5wL5ExcYc",
      country: "US",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "luis suarez",
        "luis suarez news",
        "luis suarez United States"
      ],
      summary: "Harry Kane y Luis Suárez, cara a cara: la foto que compartió el goleador uruguayo",
      detail: "Harry Kane y Luis Suárez, cara a cara: la foto que compartió el goleador uruguayo\nluis suarez is seeing increased search interest in United States.\nSource: Montevideo Portal.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "suarez",
      slug: "us-suarez-2026-07-11",
      traffic: "2000+",
      description: "La sugestiva foto de la China Suárez y Mauro Icardi arriba de un avión: “¿Cómo podés sonreír así?“",
      source: "Infobae",
      sourceUrl: "https://www.infobae.com/teleshow/2026/07/10/la-sugestiva-foto-de-la-china-suarez-y-mauro-icardi-arriba-de-un-avion-como-podes-sonreir-asi/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa7Qg3Vrv-BlOapu12dN9F3UBx32nS5EvlcLZCmXgW4AIHcpPxqX4kifc0So8",
      country: "US",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "suarez",
        "suarez news",
        "suarez United States"
      ],
      summary: "La sugestiva foto de la China Suárez y Mauro Icardi arriba de un avión: “¿Cómo podés sonreír así?“",
      detail: "La sugestiva foto de la China Suárez y Mauro Icardi arriba de un avión: “¿Cómo podés sonreír así?“\nsuarez is seeing increased search interest in United States.\nSource: Infobae.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "golden goal",
      slug: "us-golden-goal-2026-07-11",
      traffic: "2000+",
      description: "What was the golden goal, why did FIFA eliminate it, and what was the last match in which it was used?",
      source: "Diario AS",
      sourceUrl: "https://en.as.com/soccer/world-cup/what-was-the-golden-goal-why-did-fifa-eliminate-it-and-what-was-the-last-match-in-which-it-was-used-f202607-n/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTiEwxeLdX9DsvmnpPB8zvmFeuis0rSDBglhqsTJF95R4KA9L_QxdRKB6nfoMg",
      country: "US",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "golden goal",
        "golden goal news",
        "golden goal United States"
      ],
      summary: "What was the golden goal, why did FIFA eliminate it, and what was the last match in which it was used?",
      detail: "What was the golden goal, why did FIFA eliminate it, and what was the last match in which it was used?\ngolden goal is seeing increased search interest in United States.\nSource: Diario AS.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "1966 world cup",
      slug: "us-1966-world-cup-2026-07-11",
      traffic: "1000+",
      description: "Argentina midfield great Rattin dies aged 89",
      source: "Yahoo Sports",
      sourceUrl: "https://sports.yahoo.com/articles/argentina-midfield-great-rattin-dies-222432761.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTgHnDZJKfCWTY_8zUenNJ8XpaFRvYvM4-rJoAp_lqPl6kG77xGc_suTP6JuZ4",
      country: "US",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "1966 world cup",
        "1966 world cup news",
        "1966 world cup United States"
      ],
      summary: "Argentina midfield great Rattin dies aged 89",
      detail: "Argentina midfield great Rattin dies aged 89\n1966 world cup is seeing increased search interest in United States.\nSource: Yahoo Sports.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "morgan rogers",
      slug: "us-morgan-rogers-2026-07-11",
      traffic: "1000+",
      description: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c8e2n47j0j5o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN7lM4XWQ-V5hprQLKHVwU0LEohZD6uOVrb29kvJA4pZBane2noURUOzyddJo",
      country: "US",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "morgan rogers",
        "morgan rogers news",
        "morgan rogers United States"
      ],
      summary: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      detail: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche\nmorgan rogers is seeing increased search interest in United States.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  GB: [
    {
      title: "morgan rogers",
      slug: "gb-morgan-rogers-2026-07-11",
      traffic: "2000+",
      description: "Arsenal ready to finalise record £35million transfer for Club Brugge star Christos Tzolis as Trossard replacement",
      source: "The Sun",
      sourceUrl: "https://www.thesun.co.uk/sport/39696138/arsenal-champions-league-morgan-rogers-christos-tzolis-brugge/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmn0W5eaDK01BwRZXpppNQWHXk_V99JLLDuF6NwkQl6IVI36AaIYSFeqkD-zE",
      country: "GB",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "morgan rogers",
        "morgan rogers news",
        "morgan rogers United Kingdom"
      ],
      summary: "Arsenal ready to finalise record £35million transfer for Club Brugge star Christos Tzolis as Trossard replacement",
      detail: "Arsenal ready to finalise record £35million transfer for Club Brugge star Christos Tzolis as Trossard replacement\nmorgan rogers is seeing increased search interest in United Kingdom.\nSource: The Sun.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "world cup 2022",
      slug: "gb-world-cup-2022-2026-07-11",
      traffic: "500+",
      description: "World Cup 2026: Mikel Merino the unlikely hero again as Spain wait for Lamine Yamal show",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/sport/football/articles/cvg50pvejzdo",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQzpOVVrgnJjFvWvZWv3lXcbacLdtdvOHjenIwMFJ1qZY4_AGklJzaC7myhxIE",
      country: "GB",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "world cup 2022",
        "world cup 2022 news",
        "world cup 2022 United Kingdom"
      ],
      summary: "World Cup 2026: Mikel Merino the unlikely hero again as Spain wait for Lamine Yamal show",
      detail: "World Cup 2026: Mikel Merino the unlikely hero again as Spain wait for Lamine Yamal show\nworld cup 2022 is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "1966 world cup",
      slug: "gb-1966-world-cup-2026-07-11",
      traffic: "200+",
      description: "Antonio Rattin: Argentina great remembered for 1966 sending-off dies aged 89",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/sport/football/articles/cwy09z3qlppo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRTfC0MITu-scalkY0pG8LEzc0rCUsaxnKqIWkZ58EOPYhtx1yvdggFzXACVm0",
      country: "GB",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "1966 world cup",
        "1966 world cup news",
        "1966 world cup United Kingdom"
      ],
      summary: "Antonio Rattin: Argentina great remembered for 1966 sending-off dies aged 89",
      detail: "Antonio Rattin: Argentina great remembered for 1966 sending-off dies aged 89\n1966 world cup is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "rogers england",
      slug: "gb-rogers-england-2026-07-11",
      traffic: "200+",
      description: "'Brilliant' mural of Bellingham and Rogers appears",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/news/articles/c8r2zm03g4vo",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSewtLRTsNRMOMhv2hP6XITxv9lNaBYqQgQU0hzzud9qDUWzw4bkNSwpFqHOj8",
      country: "GB",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "rogers england",
        "rogers england news",
        "rogers england United Kingdom"
      ],
      summary: "'Brilliant' mural of Bellingham and Rogers appears",
      detail: "'Brilliant' mural of Bellingham and Rogers appears\nrogers england is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "rivaldo",
      slug: "gb-rivaldo-2026-07-11",
      traffic: "200+",
      description: "Ousmane Dembele explains how ‘fearless’ Kylian Mbappe advice resulted in crucial goal as France beat Morocco to secure semi-final spot",
      source: "Goal.com",
      sourceUrl: "https://www.goal.com/en/lists/ousmane-dembele-kylian-mbappe-advice-france-morocco--world-cup/bltf62c38780d938821",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRm8RCQ5rQh-2QxDlrc3E0BRcq6ylR4vrGcbB_tTQA-YWSnHmrsIWtxgQ5475Q",
      country: "GB",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "rivaldo",
        "rivaldo news",
        "rivaldo United Kingdom"
      ],
      summary: "Ousmane Dembele explains how ‘fearless’ Kylian Mbappe advice resulted in crucial goal as France beat Morocco to secure semi-final spot",
      detail: "Ousmane Dembele explains how ‘fearless’ Kylian Mbappe advice resulted in crucial goal as France beat Morocco to secure semi-final spot\nrivaldo is seeing increased search interest in United Kingdom.\nSource: Goal.com.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  DE: [
    {
      title: "morgan rogers",
      slug: "de-morgan-rogers-2026-07-11",
      traffic: "200+",
      description: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c8e2n47j0j5o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN7lM4XWQ-V5hprQLKHVwU0LEohZD6uOVrb29kvJA4pZBane2noURUOzyddJo",
      country: "DE",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "morgan rogers",
        "morgan rogers news",
        "morgan rogers Germany"
      ],
      summary: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      detail: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche\nmorgan rogers is seeing increased search interest in Germany.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "charlie kirk",
      slug: "de-charlie-kirk-2026-07-11",
      traffic: "100+",
      description: "'Devastating' evidence against Charlie Kirk murder suspect laid out in court",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c4gy12gqzpvo",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQXV-WFx3uf2pvDIiaxCegkgccbrDseauhjf3WQbBcgwzOIDBnpM1SDI0Lu4ng",
      country: "DE",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "charlie kirk",
        "charlie kirk news",
        "charlie kirk Germany"
      ],
      summary: "'Devastating' evidence against Charlie Kirk murder suspect laid out in court",
      detail: "'Devastating' evidence against Charlie Kirk murder suspect laid out in court\ncharlie kirk is seeing increased search interest in Germany.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "braut haaland",
      slug: "de-braut-haaland-2026-07-11",
      traffic: "2000+",
      description: "Erling Haaland bei WM 2026: Wieso steht der Name \"Braut\" mit auf dem National-Trikot?",
      source: "ran",
      sourceUrl: "https://ran.joyn.de/sports/fussball/wm/erling-haaland-bei-wm2026-wieso-steht-braut-mit-auf-dem-national-trikot-152110",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF4-cxPinLeNULnB7wmL9Swz174Zy2CM0kfbSn-RpGAPMYL1FsDxZouWz30ns",
      country: "DE",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "braut haaland",
        "braut haaland news",
        "braut haaland Germany"
      ],
      summary: "Erling Haaland bei WM 2026: Wieso steht der Name \"Braut\" mit auf dem National-Trikot?",
      detail: "Erling Haaland bei WM 2026: Wieso steht der Name \"Braut\" mit auf dem National-Trikot?\nbraut haaland is seeing increased search interest in Germany.\nSource: ran.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  JP: [
    {
      title: "モーガン・ロジャーズ",
      slug: "jp-モーガン・ロジャーズ-2026-07-11",
      traffic: "200+",
      description: "ロジャーズ獲得交渉への影響も？…アーセナル、ヴィラのイングランド代表DFコンサに関心か（サッカーキング）",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/0989e2ca27fdc264eed9d6d4adbabf070cb0e8f0",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrIDD73B_nUIxGPzSNGCdjU1PCMHudmrF9UQv87Q0C00zq_0V8m5B9Xafwxl0",
      country: "JP",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "モーガン・ロジャーズ",
        "モーガン・ロジャーズ news",
        "モーガン・ロジャーズ Japan"
      ],
      summary: "ロジャーズ獲得交渉への影響も？…アーセナル、ヴィラのイングランド代表DFコンサに関心か（サッカーキング）",
      detail: "ロジャーズ獲得交渉への影響も？…アーセナル、ヴィラのイングランド代表DFコンサに関心か（サッカーキング）\nモーガン・ロジャーズ is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "サカ イングランド",
      slug: "jp-サカ-イングランド-2026-07-11",
      traffic: "200+",
      description: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals",
      source: "Sports Illustrated",
      sourceUrl: "https://www.si.com/soccer/why-bukayo-saka-isnt-playing-england-vs-norway-world-cup-quarterfinals",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQxuEq9NN6457fE19fPhQshTwww5PnCuDjI-IaNViyKMKyxOURuqKQqRlF_o-Q",
      country: "JP",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "サカ イングランド",
        "サカ イングランド news",
        "サカ イングランド Japan"
      ],
      summary: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals",
      detail: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals\nサカ イングランド is seeing increased search interest in Japan.\nSource: Sports Illustrated.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ズラタン・イブラヒモヴィッチ",
      slug: "jp-ズラタン・イブラヒモヴィッチ-2026-07-11",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "JP",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "ズラタン・イブラヒモヴィッチ",
        "ズラタン・イブラヒモヴィッチ news",
        "ズラタン・イブラヒモヴィッチ Japan"
      ],
      summary: "ズラタン・イブラヒモヴィッチ is trending in Japan.",
      detail: "ズラタン・イブラヒモヴィッチ is trending in Japan.\nズラタン・イブラヒモヴィッチ is seeing increased search interest in Japan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ルーニー",
      slug: "jp-ルーニー-2026-07-11",
      traffic: "100+",
      description: "【北中米Ｗ杯】ルーニー氏の〝劇的イメチェン〟が話題 過去には植毛に６００万円…美容医療説も浮上（東スポWEB）",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/7925ceae88c06f3e1a4f17d4105c568ac4eac1b0",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR_EEJbHSy3GKTwdKRNdth_ljrwkBdNpE7lv8svFo0gRiEOZ-8Z6LZ0JZXf3rM",
      country: "JP",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "ルーニー",
        "ルーニー news",
        "ルーニー Japan"
      ],
      summary: "【北中米Ｗ杯】ルーニー氏の〝劇的イメチェン〟が話題 過去には植毛に６００万円…美容医療説も浮上（東スポWEB）",
      detail: "【北中米Ｗ杯】ルーニー氏の〝劇的イメチェン〟が話題 過去には植毛に６００万円…美容医療説も浮上（東スポWEB）\nルーニー is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ヌサ",
      slug: "jp-ヌサ-2026-07-11",
      traffic: "2000+",
      description: "約１１２億円、ヌサ争奪戦勃発 ５プレミアリーグ・クラブが２１歳ノルウェー代表ＦＷ獲得に興味（スポーツ報知）",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/68cecee64e563209356c21f15e25e92a53b1eab1",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRJSH0BgNgP8vBY8NX4UcQtQlW8o-Cgufg09Dgu-fsVHUG1987QpHYuBVIM5GE",
      country: "JP",
      date: "2026-07-11",
      pubTime: "35m ago",
      relatedQueries: [
        "ヌサ",
        "ヌサ news",
        "ヌサ Japan"
      ],
      summary: "約１１２億円、ヌサ争奪戦勃発 ５プレミアリーグ・クラブが２１歳ノルウェー代表ＦＷ獲得に興味（スポーツ報知）",
      detail: "約１１２億円、ヌサ争奪戦勃発 ５プレミアリーグ・クラブが２１歳ノルウェー代表ＦＷ獲得に興味（スポーツ報知）\nヌサ is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  CA: [
    {
      title: "stampeders vs alouettes",
      slug: "ca-stampeders-vs-alouettes-2026-07-11",
      traffic: "500+",
      description: "3 keys to victory for Calgary, Montreal in Week 6",
      source: "CFL.ca",
      sourceUrl: "https://www.cfl.ca/2026/07/10/3-keys-to-victory-for-calgary-montreal-in-week-6/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd7HPxVJJUPQ0-zps8NJ4ta5Ku1CQb-9hDMqomJFJdWyNubyGQAboHxWNuJMo",
      country: "CA",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "stampeders vs alouettes",
        "stampeders vs alouettes news",
        "stampeders vs alouettes Canada"
      ],
      summary: "3 keys to victory for Calgary, Montreal in Week 6",
      detail: "3 keys to victory for Calgary, Montreal in Week 6\nstampeders vs alouettes is seeing increased search interest in Canada.\nSource: CFL.ca.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "sûreté du québec",
      slug: "ca-sret-du-qubec-2026-07-11",
      traffic: "500+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "CA",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "sûreté du québec",
        "sûreté du québec news",
        "sûreté du québec Canada"
      ],
      summary: "sûreté du québec is trending in Canada.",
      detail: "sûreté du québec is trending in Canada.\nsûreté du québec is seeing increased search interest in Canada.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "morgan rogers",
      slug: "ca-morgan-rogers-2026-07-11",
      traffic: "200+",
      description: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c8e2n47j0j5o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN7lM4XWQ-V5hprQLKHVwU0LEohZD6uOVrb29kvJA4pZBane2noURUOzyddJo",
      country: "CA",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "morgan rogers",
        "morgan rogers news",
        "morgan rogers Canada"
      ],
      summary: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche",
      detail: "Football gossip: Rogers, Mora, Spence, Vozinha, Emersonn, Akliouche\nmorgan rogers is seeing increased search interest in Canada.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AU: [
    {
      title: "cairns marathon",
      slug: "au-cairns-marathon-2026-07-11",
      traffic: "100+",
      description: "Why this Cairns man is running four marathons in just four days",
      source: "The Cairns Post",
      sourceUrl: "https://www.cairnspost.com.au/news/cairns/hyperlocal/my-therapy-kevin-durose-on-tackling-four-marathons-to-inspire-others/news-story/a7169308cea2feadbd47d36ecb33693a",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbVdmYbGvb0KWgAC2TJeDA0qNU2GMLnnPQPRJ1mHzSgTTfJqAt7A_HwXlN-_8",
      country: "AU",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "cairns marathon",
        "cairns marathon news",
        "cairns marathon Australia"
      ],
      summary: "Why this Cairns man is running four marathons in just four days",
      detail: "Why this Cairns man is running four marathons in just four days\ncairns marathon is seeing increased search interest in Australia.\nSource: The Cairns Post.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ro khanna",
      slug: "au-ro-khanna-2026-07-11",
      traffic: "200+",
      description: "US Democrat Ro Khanna says he was detained by armed Israeli settlers",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c0qyk9jwq9no",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRtbGoh6rBnk5gSLYjBCpdZ3DESVMRdc0chMSFA31VuW-PS8FQkfJqlLAOvT_s",
      country: "AU",
      date: "2026-07-11",
      pubTime: "35m ago",
      relatedQueries: [
        "ro khanna",
        "ro khanna news",
        "ro khanna Australia"
      ],
      summary: "US Democrat Ro Khanna says he was detained by armed Israeli settlers",
      detail: "US Democrat Ro Khanna says he was detained by armed Israeli settlers\nro khanna is seeing increased search interest in Australia.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "haaland age",
      slug: "au-haaland-age-2026-07-11",
      traffic: "200+",
      description: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      source: "ESPN",
      sourceUrl: "https://www.espn.com/soccer/story/_/id/49316632/erling-haaland-norway-world-cup-manchester-city-england-striker-analysis-lionel-messi",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo3UWS8lySMZ3OehFp0S7dZaQWY9ZV_SxuYSiKq0YrrxIkeTknkp7qDQIKV8g",
      country: "AU",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "haaland age",
        "haaland age news",
        "haaland age Australia"
      ],
      summary: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      detail: "Forget Messi & Co., because this is Erling Haaland's World Cup\nhaaland age is seeing increased search interest in Australia.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  FR: [
    {
      title: "magnus carlsen",
      slug: "fr-magnus-carlsen-2026-07-11",
      traffic: "2000+",
      description: "REPORTAGE. \"Elle est impressionnante\" : à Montauban, les reines de l’échiquier sont au cœur du Festival des 400 coups",
      source: "ladepeche.fr",
      sourceUrl: "https://www.ladepeche.fr/2026/07/11/reportage-elle-est-impressionnante-a-montauban-les-reines-de-lechiquier-sont-au-coeur-du-festival-des-400-coups-13464844.php",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGAs82XWaYfShJPVBv-KFto6Tc_2SlBturmlAVictK92HWNcdv4ZNslFVMcms",
      country: "FR",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "magnus carlsen",
        "magnus carlsen news",
        "magnus carlsen France"
      ],
      summary: "REPORTAGE. \"Elle est impressionnante\" : à Montauban, les reines de l’échiquier sont au cœur du Festival des 400 coups",
      detail: "REPORTAGE. \"Elle est impressionnante\" : à Montauban, les reines de l’échiquier sont au cœur du Festival des 400 coups\nmagnus carlsen is seeing increased search interest in France.\nSource: ladepeche.fr.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ali khamenei",
      slug: "fr-ali-khamenei-2026-07-11",
      traffic: "2000+",
      description: "Iran supreme leader calls for revenge for father's killing",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/cj9gkpp0dkeo",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQiFbsPNH4Vy8fq5bmTfzXzWilpbP69lYhq2oOESBeiOTe_4eqYOXCgbUCS_KU",
      country: "FR",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "ali khamenei",
        "ali khamenei news",
        "ali khamenei France"
      ],
      summary: "Iran supreme leader calls for revenge for father's killing",
      detail: "Iran supreme leader calls for revenge for father's killing\nali khamenei is seeing increased search interest in France.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  KR: [
    {
      title: "사건",
      slug: "kr-사건-2026-07-11",
      traffic: "2000+",
      description: "‘장윤기 사건’ 공방 계속…“전면 재수사해야”·“보완수사권 폐지 안 돼”",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260712072039813",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSbNO0he5sjT62ZiLNoAzgJ1qyYQ69ppymKc8t7amuBjxXfZnv3jTKEWIH6tSo",
      country: "KR",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "사건",
        "사건 news",
        "사건 South Korea"
      ],
      summary: "‘장윤기 사건’ 공방 계속…“전면 재수사해야”·“보완수사권 폐지 안 돼”",
      detail: "‘장윤기 사건’ 공방 계속…“전면 재수사해야”·“보완수사권 폐지 안 돼”\n사건 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "고우석",
      slug: "kr-고우석-2026-07-11",
      traffic: "2000+",
      description: "안우진도 '뭉클'했던 고우석 美 데뷔 \"형 너무 멋있더라, 버티고 이겨내는 것 보니...\"",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260712033437620",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTpWDcbnJ8wO3fJqQkiB6hBPrCQbO6o6eiWtbwpCMrtsSCas1RDpcq8OzrOhyo",
      country: "KR",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "고우석",
        "고우석 news",
        "고우석 South Korea"
      ],
      summary: "안우진도 '뭉클'했던 고우석 美 데뷔 \"형 너무 멋있더라, 버티고 이겨내는 것 보니...\"",
      detail: "안우진도 '뭉클'했던 고우석 美 데뷔 \"형 너무 멋있더라, 버티고 이겨내는 것 보니...\"\n고우석 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "주드 벨링엄",
      slug: "kr-주드-벨링엄-2026-07-11",
      traffic: "500+",
      description: "투헬: 뭐?! 팔 부상이라고?!! 스톤스&라이스: 장난~ㅋㅋ... 오늘도 훈훈한 잉글랜드 락커룸",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/BL8SP9jJuj",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUVJFWeaOvO04dbEgocndiO8zkSyu9RCp1azeXwL7F1O3Fo6IqNZrOsfJ2FPU",
      country: "KR",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "주드 벨링엄",
        "주드 벨링엄 news",
        "주드 벨링엄 South Korea"
      ],
      summary: "투헬: 뭐?! 팔 부상이라고?!! 스톤스&라이스: 장난~ㅋㅋ... 오늘도 훈훈한 잉글랜드 락커룸",
      detail: "투헬: 뭐?! 팔 부상이라고?!! 스톤스&라이스: 장난~ㅋㅋ... 오늘도 훈훈한 잉글랜드 락커룸\n주드 벨링엄 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "김도영",
      slug: "kr-김도영-2026-07-11",
      traffic: "500+",
      description: "홈런더비 눈길 끈 김도영 신발 \"중학생 팬이 준 선물...올스타전서도 신을 것\"",
      source: "조선일보",
      sourceUrl: "https://www.chosun.com/sports/sports_general/2026/07/11/MZFWTPI2BJAMBGZWD4YYDZIMC4/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwKFrV5lu68ECbVKbcU7nobiKKrEm4rJZKmiWeOyW-rPSdDTkjp8Mdg-qZREI",
      country: "KR",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "김도영",
        "김도영 news",
        "김도영 South Korea"
      ],
      summary: "홈런더비 눈길 끈 김도영 신발 \"중학생 팬이 준 선물...올스타전서도 신을 것\"",
      detail: "홈런더비 눈길 끈 김도영 신발 \"중학생 팬이 준 선물...올스타전서도 신을 것\"\n김도영 is seeing increased search interest in South Korea.\nSource: 조선일보.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "노르웨이 월드컵",
      slug: "kr-노르웨이-월드컵-2026-07-11",
      traffic: "200+",
      description: "\"바이킹처럼 노를 저어라\"...노르웨이의 월드컵 돌풍 [앵커리포트]",
      source: "YTN",
      sourceUrl: "https://www.ytn.co.kr/_ln/0107_202607101715580772",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR2PVtBPs3jkC22pf8S23adfvEMQ1jtfpPpymuXXfwW5Zb7q7s-VoV93PVbTo",
      country: "KR",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "노르웨이 월드컵",
        "노르웨이 월드컵 news",
        "노르웨이 월드컵 South Korea"
      ],
      summary: "\"바이킹처럼 노를 저어라\"...노르웨이의 월드컵 돌풍 [앵커리포트]",
      detail: "\"바이킹처럼 노를 저어라\"...노르웨이의 월드컵 돌풍 [앵커리포트]\n노르웨이 월드컵 is seeing increased search interest in South Korea.\nSource: YTN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IT: [
    {
      title: "ostigard",
      slug: "it-ostigard-2026-07-11",
      traffic: "200+",
      description: "Norvegia, i 5 vichinghi d'Italia: Heggem il più utilizzato. Pedersen e Ostigard in gol",
      source: "La Gazzetta dello Sport",
      sourceUrl: "https://www.gazzetta.it/calcio/fantanews/10-07-2026/mondiali-norvegia-serie-a-heggem-piu-utilizzato-pedersen-ostigard-in-gol.shtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQsdzyzF84DIkbg5iI-bBL4RpioCH0ctZIMaZxxnRz68zxAC-v1hMSCn9d00Dw",
      country: "IT",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "ostigard",
        "ostigard news",
        "ostigard Italy"
      ],
      summary: "Norvegia, i 5 vichinghi d'Italia: Heggem il più utilizzato. Pedersen e Ostigard in gol",
      detail: "Norvegia, i 5 vichinghi d'Italia: Heggem il più utilizzato. Pedersen e Ostigard in gol\nostigard is seeing increased search interest in Italy.\nSource: La Gazzetta dello Sport.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "meteo rimini",
      slug: "it-meteo-rimini-2026-07-11",
      traffic: "500+",
      description: "Allerta ordinaria (gialla), nel pomeriggio temporali intensi",
      source: "Ufficio Stampa della Provincia autonoma di Trento",
      sourceUrl: "https://www.ufficiostampa.provincia.tn.it/Comunicati/Allerta-ordinaria-gialla-nel-pomeriggio-temporali-intensi",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR4i0userGQ_FbfDKDNTY3HqxiF1SZ16key3AfvI-aYdGOuBjuUXxOajPR8VHs",
      country: "IT",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "meteo rimini",
        "meteo rimini news",
        "meteo rimini Italy"
      ],
      summary: "Allerta ordinaria (gialla), nel pomeriggio temporali intensi",
      detail: "Allerta ordinaria (gialla), nel pomeriggio temporali intensi\nmeteo rimini is seeing increased search interest in Italy.\nSource: Ufficio Stampa della Provincia autonoma di Trento.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "gianni infantino",
      slug: "it-gianni-infantino-2026-07-11",
      traffic: "500+",
      description: "Ci volevano Trump e il caso Balogun per far sentire l'Europa unita",
      source: "La Gazzetta dello Sport",
      sourceUrl: "https://www.gazzetta.it/Calcio/Mondiali/11-07-2026/trump-balogun-europa-commento-ravelli-gazzetta.shtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTu19N3qOESk43w8tfhclB5lmAPdzVyhWnhHmjPK9v0JO8o0USA53eyfFxNG-Y",
      country: "IT",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "gianni infantino",
        "gianni infantino news",
        "gianni infantino Italy"
      ],
      summary: "Ci volevano Trump e il caso Balogun per far sentire l'Europa unita",
      detail: "Ci volevano Trump e il caso Balogun per far sentire l'Europa unita\ngianni infantino is seeing increased search interest in Italy.\nSource: La Gazzetta dello Sport.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "mondiali calcio norvegia inghilterra",
      slug: "it-mondiali-calcio-norvegia-inghilterra-2026-07-11",
      traffic: "200+",
      description: "LIVE Minuto di silenzio per Adams. Lutto Argentina: è morto Rattìn, era ai Mondiali del 1966",
      source: "La Gazzetta dello Sport",
      sourceUrl: "https://www.gazzetta.it/Calcio/Mondiali/11-07-2026/live-mondiali-2026-cosa-succede-tra-usa-canada-e-messico.shtml",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ9EZhcLWnECOPWeMYImQY78_wS8wcjrGNUzUTdSmvsSpyrtoetFSsK0yUeKi0",
      country: "IT",
      date: "2026-07-11",
      pubTime: "35m ago",
      relatedQueries: [
        "mondiali calcio norvegia inghilterra",
        "mondiali calcio norvegia inghilterra news",
        "mondiali calcio norvegia inghilterra Italy"
      ],
      summary: "LIVE Minuto di silenzio per Adams. Lutto Argentina: è morto Rattìn, era ai Mondiali del 1966",
      detail: "LIVE Minuto di silenzio per Adams. Lutto Argentina: è morto Rattìn, era ai Mondiali del 1966\nmondiali calcio norvegia inghilterra is seeing increased search interest in Italy.\nSource: La Gazzetta dello Sport.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  BR: [
    {
      title: "ronaldo fenomeno",
      slug: "br-ronaldo-fenomeno-2026-07-11",
      traffic: "500+",
      description: "Ronaldo Fenômeno brinca com recordes na Copa do Mundo: \"Virou várzea, todo mundo me passando\"",
      source: "ge",
      sourceUrl: "https://ge.globo.com/futebol/copa-do-mundo/noticia/2026/07/11/ronaldo-fenomeno-brinca-com-recordes-na-copa-do-mundo-virou-varzea-todo-mundo-me-passando.ghtml",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQCFekM3ewBdKq_czL71g2ZcUlEXEoCvoFhTFXOjKKc6XvYG2Gx7IeIetUOZIE",
      country: "BR",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "ronaldo fenomeno",
        "ronaldo fenomeno news",
        "ronaldo fenomeno Brazil"
      ],
      summary: "Ronaldo Fenômeno brinca com recordes na Copa do Mundo: \"Virou várzea, todo mundo me passando\"",
      detail: "Ronaldo Fenômeno brinca com recordes na Copa do Mundo: \"Virou várzea, todo mundo me passando\"\nronaldo fenomeno is seeing increased search interest in Brazil.\nSource: ge.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "bye bye caju",
      slug: "br-bye-bye-caju-2026-07-11",
      traffic: "200+",
      description: "Liniker abre turnê de despedida da era \"Caju\" e famosos curtem show em São Paulo",
      source: "Gshow",
      sourceUrl: "https://gshow.globo.com/cultura-pop/famosos/noticia/liniker-abre-turne-de-despedida-da-era-caju-e-famosos-curtem-show-em-sao-paulo.ghtml",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSKaucp9ogBHfnolJXpFpv6yxT5sg8p_ZCyWXpQrT8B5oe56iXV1wvoFyB56zA",
      country: "BR",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "bye bye caju",
        "bye bye caju news",
        "bye bye caju Brazil"
      ],
      summary: "Liniker abre turnê de despedida da era \"Caju\" e famosos curtem show em São Paulo",
      detail: "Liniker abre turnê de despedida da era \"Caju\" e famosos curtem show em São Paulo\nbye bye caju is seeing increased search interest in Brazil.\nSource: Gshow.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ponte",
      slug: "br-ponte-2026-07-11",
      traffic: "200+",
      description: "Nota à imprensa – Desvio de tráfego ponte Anita Garibaldi",
      source: "Prefeitura de Laguna -",
      sourceUrl: "https://laguna.sc.gov.br/nota-a-imprensa-desvio-de-trafego-ponte-anita-garibaldi/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP9dQi8N3zGVkCPZ5ZuxHADMmVen-nym_YK-WjQaVjDapwELszVNLsCJoydr8",
      country: "BR",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "ponte",
        "ponte news",
        "ponte Brazil"
      ],
      summary: "Nota à imprensa – Desvio de tráfego ponte Anita Garibaldi",
      detail: "Nota à imprensa – Desvio de tráfego ponte Anita Garibaldi\nponte is seeing increased search interest in Brazil.\nSource: Prefeitura de Laguna -.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IN: [
    {
      title: "morgan rogers",
      slug: "in-morgan-rogers-2026-07-11",
      traffic: "500+",
      description: "Transfer rumors, news: Arsenal must pay British-record fee to sign Villa's Rogers",
      source: "ESPN India",
      sourceUrl: "https://www.espn.in/football/story/_/id/49312380/transfer-rumors-news-arsenal-tottenham-rb-leipzig-norway-antonio-nusa",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6aC_vYpGXI8JwVPc4x48YtS-LGCjalZvDRBt5yLQ9uUzUUFmvUC2frcwd2zw",
      country: "IN",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "morgan rogers",
        "morgan rogers news",
        "morgan rogers India"
      ],
      summary: "Transfer rumors, news: Arsenal must pay British-record fee to sign Villa's Rogers",
      detail: "Transfer rumors, news: Arsenal must pay British-record fee to sign Villa's Rogers\nmorgan rogers is seeing increased search interest in India.\nSource: ESPN India.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  ES: [
    {
      title: "gol anulado noruega",
      slug: "es-gol-anulado-noruega-2026-07-11",
      traffic: "500+",
      description: "La regla 'anti-Arsenal' que ha anulado el 2-1 de Noruega ante Inglaterra",
      source: "MARCA",
      sourceUrl: "https://www.marca.com/futbol/mundial/2026/07/12/regla-anti-arsenal-anulado-2-1-noruega-inglaterra.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTMyCdq3lglIgM2P3b8JDzfYa61TjmoOFh0L9lVb3TZsye1kMbQg6XEZ5AGbg",
      country: "ES",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "gol anulado noruega",
        "gol anulado noruega news",
        "gol anulado noruega Spain"
      ],
      summary: "La regla 'anti-Arsenal' que ha anulado el 2-1 de Noruega ante Inglaterra",
      detail: "La regla 'anti-Arsenal' que ha anulado el 2-1 de Noruega ante Inglaterra\ngol anulado noruega is seeing increased search interest in Spain.\nSource: MARCA.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  CH: [
    {
      title: "braut haaland",
      slug: "ch-braut-haaland-2026-07-11",
      traffic: "200+",
      description: "If you ask Americans, Norway's Erling Haaland is already a winner",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/ceqd3l4v7reo",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRzmoC7koqCAwS76rI05dhT7HJgntsGwxry5gk_1FLgoif7JmfDC6q-igjneQs",
      country: "CH",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "braut haaland",
        "braut haaland news",
        "braut haaland Switzerland"
      ],
      summary: "If you ask Americans, Norway's Erling Haaland is already a winner",
      detail: "If you ask Americans, Norway's Erling Haaland is already a winner\nbraut haaland is seeing increased search interest in Switzerland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "wm",
      slug: "ch-wm-2026-07-11",
      traffic: "10000+",
      description: "Livestream: Argentinien vs Schweiz (So. 12.07.2026 03:00) - WM Männer - Fussball Resultate",
      source: "SRF",
      sourceUrl: "https://www.srf.ch/sport/resultcenter/live/football/1835738",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTwwB6_z8cbH6xfhq8pPq6UajXCEZR-9UUowekqxqya1WkJmId_2eXp2cspSHE",
      country: "CH",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "wm",
        "wm news",
        "wm Switzerland"
      ],
      summary: "Livestream: Argentinien vs Schweiz (So. 12.07.2026 03:00) - WM Männer - Fussball Resultate",
      detail: "Livestream: Argentinien vs Schweiz (So. 12.07.2026 03:00) - WM Männer - Fussball Resultate\nwm is seeing increased search interest in Switzerland.\nSource: SRF.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "match",
      slug: "ch-match-2026-07-11",
      traffic: "200+",
      description: "Catherine cheers on William at charity polo match",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c1wyvjllwv9o",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMImvuCXW-h8O3FoBAFWyd3qtsyWzKu4_fU3XWsG0u74o6hmF4oAUwVkighwQ",
      country: "CH",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "match",
        "match news",
        "match Switzerland"
      ],
      summary: "Catherine cheers on William at charity polo match",
      detail: "Catherine cheers on William at charity polo match\nmatch is seeing increased search interest in Switzerland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "pickford",
      slug: "ch-pickford-2026-07-11",
      traffic: "500+",
      description: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/cj9gknxm91vo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSr4rFPxASmFh5_-huGzZ6Q1YrUyCY5qFpYSGdovGM47MoO7tw8arIe6s0Jtzo",
      country: "CH",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "pickford",
        "pickford news",
        "pickford Switzerland"
      ],
      summary: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      detail: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves\npickford is seeing increased search interest in Switzerland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  SE: [
    {
      title: "ronaldo",
      slug: "se-ronaldo-2026-07-11",
      traffic: "500+",
      description: "Did Cristiano Ronaldo cry? The hotly debated answer cost millions of dollars",
      source: "CNN",
      sourceUrl: "https://www.cnn.com/2026/07/11/business/cristiano-ronaldo-crying-world-cup-bet-cec",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTVXyaVvAUIZYqjRrVIBqIl8TcxF0Aiaz5KVV3pn7d_bmkD8TecElBOkvc4Dao",
      country: "SE",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "ronaldo",
        "ronaldo news",
        "ronaldo Sweden"
      ],
      summary: "Did Cristiano Ronaldo cry? The hotly debated answer cost millions of dollars",
      detail: "Did Cristiano Ronaldo cry? The hotly debated answer cost millions of dollars\nronaldo is seeing increased search interest in Sweden.\nSource: CNN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "suarez",
      slug: "se-suarez-2026-07-11",
      traffic: "500+",
      description: "Corte ordena captura del congresista del Pacto Histórico, Pedro Suárez, por caso que involucra a condenado por tráfico de drogas",
      source: "Revista Semana",
      sourceUrl: "https://www.semana.com/nacion/articulo/corte-ordena-captura-del-congresista-del-pacto-historico-pedro-suarez-por-caso-que-involucra-a-condenado-por-trafico-de-drogas/202649/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnINM_kFoReYFi8nlHlr7f-E6ZI9Ga8z8eXLO5sq3nSMgbfhx1P_JycM88F_s",
      country: "SE",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "suarez",
        "suarez news",
        "suarez Sweden"
      ],
      summary: "Corte ordena captura del congresista del Pacto Histórico, Pedro Suárez, por caso que involucra a condenado por tráfico de drogas",
      detail: "Corte ordena captura del congresista del Pacto Histórico, Pedro Suárez, por caso que involucra a condenado por tráfico de drogas\nsuarez is seeing increased search interest in Sweden.\nSource: Revista Semana.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "argentina vs switzerland",
      slug: "se-argentina-vs-switzerland-2026-07-11",
      traffic: "100+",
      description: "Álvarez's return could be Argentina's antidote to their Messi dependency",
      source: "ESPN",
      sourceUrl: "https://www.espn.co.uk/football/story/_/id/49325317/julian-alvarez-return-argentina-antidote-their-lionel-messi-dependency-world-cup",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbIRdjyrwi6TAIqii1DIuiXkTBvCk_kF53ooo3kDYbRJNLBnG82Q5QSTGdzpI",
      country: "SE",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "argentina vs switzerland",
        "argentina vs switzerland news",
        "argentina vs switzerland Sweden"
      ],
      summary: "Álvarez's return could be Argentina's antidote to their Messi dependency",
      detail: "Álvarez's return could be Argentina's antidote to their Messi dependency\nargentina vs switzerland is seeing increased search interest in Sweden.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  MX: [
    {
      title: "quien gano hoy en el mundial",
      slug: "mx-quien-gano-hoy-en-el-mundial-2026-07-11",
      traffic: "2000+",
      description: "Deportes",
      source: "La Jornada",
      sourceUrl: "https://www.jornada.com.mx/2026/07/11/deportes",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSQgHE71us7iB7xN1_hhOOBe8OhmX8kyCVnPqF5pR8qwmKBxXwvHTlBPOf6_DY",
      country: "MX",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "quien gano hoy en el mundial",
        "quien gano hoy en el mundial news",
        "quien gano hoy en el mundial Mexico"
      ],
      summary: "Deportes",
      detail: "Deportes\nquien gano hoy en el mundial is seeing increased search interest in Mexico.\nSource: La Jornada.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  NO: [
    {
      title: "vg.no",
      slug: "no-vgno-2026-07-11",
      traffic: "200+",
      description: "Fotballinfluencer om den norske spilleren: –⁠ Elsker temperamentet hans",
      source: "VG",
      sourceUrl: "https://www.vg.no/sport/i/vrxx5p/fotballinfluencer-ivana-knoll-om-den-norske-spilleren-elsker-temperamentet-hans",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkVwf8tI4RmyYyNNvvJ3z9ABotq_JWXQmv-ziVJsZ2kNpDd29RBauS2KQfVs8",
      country: "NO",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "vg.no",
        "vg.no news",
        "vg.no Norway"
      ],
      summary: "Fotballinfluencer om den norske spilleren: –⁠ Elsker temperamentet hans",
      detail: "Fotballinfluencer om den norske spilleren: –⁠ Elsker temperamentet hans\nvg.no is seeing increased search interest in Norway.\nSource: VG.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  DK: [
    {
      title: "braut haaland",
      slug: "dk-braut-haaland-2026-07-11",
      traffic: "100+",
      description: "'Du kan komme til at se rigtig, rigtig dum ud': Haaland er blevet VM's bøhmand",
      source: "dr.dk",
      sourceUrl: "https://www.dr.dk/sporten/fodbold/vm/du-kan-komme-til-se-rigtig-rigtig-dum-ud-haaland-er-blevet-vm-s-boehmand",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN9BFJeZAWZ0gMw2ylsfNan3grpAgi_2ydvrgO3Mhxep3jzYs_rsS3SNkKwPc",
      country: "DK",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "braut haaland",
        "braut haaland news",
        "braut haaland Denmark"
      ],
      summary: "'Du kan komme til at se rigtig, rigtig dum ud': Haaland er blevet VM's bøhmand",
      detail: "'Du kan komme til at se rigtig, rigtig dum ud': Haaland er blevet VM's bøhmand\nbraut haaland is seeing increased search interest in Denmark.\nSource: dr.dk.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "bbc",
      slug: "dk-bbc-2026-07-11",
      traffic: "100+",
      description: "Meet the crypto billionaires building a world where money buys you a vote",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/cly8eqyj8e2o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRzyg-GKvJvaDCX2gVvwXr73_rZ3cH7ySaFUZ7EV1PsfdvN4mAisn5RT6e_X4c",
      country: "DK",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "bbc",
        "bbc news",
        "bbc Denmark"
      ],
      summary: "Meet the crypto billionaires building a world where money buys you a vote",
      detail: "Meet the crypto billionaires building a world where money buys you a vote\nbbc is seeing increased search interest in Denmark.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  BE: [
    {
      title: "wk",
      slug: "be-wk-2026-07-11",
      traffic: "10000+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "BE",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "wk",
        "wk news",
        "wk Belgium"
      ],
      summary: "wk is trending in Belgium.",
      detail: "wk is trending in Belgium.\nwk is seeing increased search interest in Belgium.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AT: [
    {
      title: "solarstrom",
      slug: "at-solarstrom-2026-07-11",
      traffic: "100+",
      description: "Salz-Technologie – China liefert Solarstrom auch bei Nacht",
      source: "Heute",
      sourceUrl: "https://www.heute.at/s/china-liefert-solarstrom-auch-bei-nacht-120221874",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQcshNPP46PHOAyx04lbf1fTFBhLogieW8Nawj8-TI_6s3FEZoNeXV8g0EWqx4",
      country: "AT",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "solarstrom",
        "solarstrom news",
        "solarstrom Austria"
      ],
      summary: "Salz-Technologie – China liefert Solarstrom auch bei Nacht",
      detail: "Salz-Technologie – China liefert Solarstrom auch bei Nacht\nsolarstrom is seeing increased search interest in Austria.\nSource: Heute.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "braut haaland",
      slug: "at-braut-haaland-2026-07-11",
      traffic: "200+",
      description: "Norwegen-Trainer kritisiert Haaland vor England-Spiel",
      source: "oe24.at",
      sourceUrl: "https://www.oe24.at/a/norwegen-trainer-kritisiert-haaland-vor-england-spiel-900099119",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYo2n1PlvYtYSiHTEyK8TnNL5oOO_esnRyW0kn7gwS2FMp2R4RuPx4i33nbT8",
      country: "AT",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "braut haaland",
        "braut haaland news",
        "braut haaland Austria"
      ],
      summary: "Norwegen-Trainer kritisiert Haaland vor England-Spiel",
      detail: "Norwegen-Trainer kritisiert Haaland vor England-Spiel\nbraut haaland is seeing increased search interest in Austria.\nSource: oe24.at.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "gala",
      slug: "at-gala-2026-07-11",
      traffic: "100+",
      description: "Machtdemonstration gegen Paris - Vikings nicht zu stoppen!",
      source: "LAOLA1",
      sourceUrl: "https://www.laola1.at/de/red/sport-mix/football/sonstiges/machtdemonstration-gegen-paris---vikings-nicht-zu-stoppen-/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ2KmO-kaHdLAU333gwDqHt0p1fUFNhaAZVyIjXrAc7Gel2A4EW2wNc5F-_BnI",
      country: "AT",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "gala",
        "gala news",
        "gala Austria"
      ],
      summary: "Machtdemonstration gegen Paris - Vikings nicht zu stoppen!",
      detail: "Machtdemonstration gegen Paris - Vikings nicht zu stoppen!\ngala is seeing increased search interest in Austria.\nSource: LAOLA1.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IE: [
    {
      title: "explosive diarrhea outbreak",
      slug: "ie-explosive-diarrhea-outbreak-2026-07-11",
      traffic: "1000+",
      description: "What to know about 'explosive diarrhoea' parasite outbreak in US",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c621m66qm76o",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6CdZ0JyBKhXKZRxLGGSPZDzxzaaPCQHnOQaSiGzPxCoaMEesozzcY2L3kg08",
      country: "IE",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "explosive diarrhea outbreak",
        "explosive diarrhea outbreak news",
        "explosive diarrhea outbreak Ireland"
      ],
      summary: "What to know about 'explosive diarrhoea' parasite outbreak in US",
      detail: "What to know about 'explosive diarrhoea' parasite outbreak in US\nexplosive diarrhea outbreak is seeing increased search interest in Ireland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "tracy cortez",
      slug: "ie-tracy-cortez-2026-07-11",
      traffic: "100+",
      description: "UFC stunner Tracy Cortez loving World Cup fever despite her beloved Mexico crashing out against England",
      source: "The Irish Sun",
      sourceUrl: "https://www.thesun.ie/sport/17267027/ufc-tracey-cortez-loves-world-cup-fever-mexico-out/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQH4qLFwVdKp7ICii9I_jgafT5HRq2LmwacYxg7q6ubgUuYAh4K93mZSadx9uM",
      country: "IE",
      date: "2026-07-11",
      pubTime: "15m ago",
      relatedQueries: [
        "tracy cortez",
        "tracy cortez news",
        "tracy cortez Ireland"
      ],
      summary: "UFC stunner Tracy Cortez loving World Cup fever despite her beloved Mexico crashing out against England",
      detail: "UFC stunner Tracy Cortez loving World Cup fever despite her beloved Mexico crashing out against England\ntracy cortez is seeing increased search interest in Ireland.\nSource: The Irish Sun.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "saka",
      slug: "ie-saka-2026-07-11",
      traffic: "200+",
      description: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals",
      source: "Sports Illustrated",
      sourceUrl: "https://www.si.com/soccer/why-bukayo-saka-isnt-playing-england-vs-norway-world-cup-quarterfinals",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQxuEq9NN6457fE19fPhQshTwww5PnCuDjI-IaNViyKMKyxOURuqKQqRlF_o-Q",
      country: "IE",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "saka",
        "saka news",
        "saka Ireland"
      ],
      summary: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals",
      detail: "Why Bukayo Saka Isn’t Playing for England vs. Norway—World Cup Quarterfinals\nsaka is seeing increased search interest in Ireland.\nSource: Sports Illustrated.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  SG: [
    {
      title: "jordan pickford",
      slug: "sg-jordan-pickford-2026-07-11",
      traffic: "100+",
      description: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/cj9gknxm91vo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSr4rFPxASmFh5_-huGzZ6Q1YrUyCY5qFpYSGdovGM47MoO7tw8arIe6s0Jtzo",
      country: "SG",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "jordan pickford",
        "jordan pickford news",
        "jordan pickford Singapore"
      ],
      summary: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      detail: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves\njordan pickford is seeing increased search interest in Singapore.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "世界杯2026",
      slug: "sg-世界杯2026-2026-07-11",
      traffic: "100+",
      description: "被问和哈兰德谁更出色 凯恩：我们是完全不同类型",
      source: "联合早报",
      sourceUrl: "https://www.zaobao.com.sg/news/sports/story20260711-9349827",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRzzrp0E6W2CgDWWqxzfUHyPv6C9sir4bqHG8yFnpPdyLkEGqzwrycxATuSp0I",
      country: "SG",
      date: "2026-07-11",
      pubTime: "25m ago",
      relatedQueries: [
        "世界杯2026",
        "世界杯2026 news",
        "世界杯2026 Singapore"
      ],
      summary: "被问和哈兰德谁更出色 凯恩：我们是完全不同类型",
      detail: "被问和哈兰德谁更出色 凯恩：我们是完全不同类型\n世界杯2026 is seeing increased search interest in Singapore.\nSource: 联合早报.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ørjan nyland",
      slug: "sg-rjan-nyland-2026-07-11",
      traffic: "100+",
      description: "Erling Haaland says Brazil win 'greatest game' in Norway history",
      source: "ESPN Singapore",
      sourceUrl: "https://www.espn.com.sg/soccer/story/_/id/49281422/erling-haaland-brazil-win-greatest-game-norway-history",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqMRhJGwgJRfbxj_C7_mf81S2GVkpoQL0mzY05yHX2dpkFRyBRIFrLvjWKU8c",
      country: "SG",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "ørjan nyland",
        "ørjan nyland news",
        "ørjan nyland Singapore"
      ],
      summary: "Erling Haaland says Brazil win 'greatest game' in Norway history",
      detail: "Erling Haaland says Brazil win 'greatest game' in Norway history\nørjan nyland is seeing increased search interest in Singapore.\nSource: ESPN Singapore.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IL: [
    {
      title: "אנדריאס שיילדרופ",
      slug: "il-אנדריאס-שיילדרופ-2026-07-11",
      traffic: "200+",
      description: "העבר הפלילי המזעזע של כובש השער המרהיב מול אנגליה",
      source: "ספורט 1",
      sourceUrl: "https://sport1.maariv.co.il/mundial-2026/article/1895895/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSXiBCmNQdeuWTyMiNwDfdO2A1VC09WjYX22cWufinp57jj_pT8JAWp76D1PEk",
      country: "IL",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "אנדריאס שיילדרופ",
        "אנדריאס שיילדרופ news",
        "אנדריאס שיילדרופ Israel"
      ],
      summary: "העבר הפלילי המזעזע של כובש השער המרהיב מול אנגליה",
      detail: "העבר הפלילי המזעזע של כובש השער המרהיב מול אנגליה\nאנדריאס שיילדרופ is seeing increased search interest in Israel.\nSource: ספורט 1.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "fifa",
      slug: "il-fifa-2026-07-11",
      traffic: "200+",
      description: "World Cup 2026: Fifa official refuses to answer ban questions from BBC",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c4gy1j87e1yo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQW1BRdaWHCE3CWSzTEVfLQlBUr5eW6MnS3nj9FcQSPgJzW--Zq6oskHoH45gE",
      country: "IL",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "fifa",
        "fifa news",
        "fifa Israel"
      ],
      summary: "World Cup 2026: Fifa official refuses to answer ban questions from BBC",
      detail: "World Cup 2026: Fifa official refuses to answer ban questions from BBC\nfifa is seeing increased search interest in Israel.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "כאן",
      slug: "il-כאן-2026-07-11",
      traffic: "1000+",
      description: "הממד הפוליטי של כל מבנה ופיסת נוף נוכחים כאן במלוא חריפותם",
      source: "הארץ",
      sourceUrl: "https://www.haaretz.co.il/gallery/art/artreview/2026-07-08/ty-article-magazine/.premium/0000019f-3b5d-d238-a9ff-bf5d025b0000",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT7K3P2jDY7TwMtjTeaEO-ry5MSbEnG-0tkcEegBuKn9Jw8uLtrTQS6DgCPkF0",
      country: "IL",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "כאן",
        "כאן news",
        "כאן Israel"
      ],
      summary: "הממד הפוליטי של כל מבנה ופיסת נוף נוכחים כאן במלוא חריפותם",
      detail: "הממד הפוליטי של כל מבנה ופיסת נוף נוכחים כאן במלוא חריפותם\nכאן is seeing increased search interest in Israel.\nSource: הארץ.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ארלינג הולאנד",
      slug: "il-ארלינג-הולאנד-2026-07-11",
      traffic: "200+",
      description: "כובש את ארה\"ב: תופעת ארלינג הולאנד",
      source: "Sport5",
      sourceUrl: "https://www.sport5.co.il/articles.aspx?FolderID=5166&docID=551846",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1mHOFMZ357cRi5PDgR1yBRnBhnKltxQwRQfrqG92P8BHegJ4_4sOGUvtWDvM",
      country: "IL",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "ארלינג הולאנד",
        "ארלינג הולאנד news",
        "ארלינג הולאנד Israel"
      ],
      summary: "כובש את ארה\"ב: תופעת ארלינג הולאנד",
      detail: "כובש את ארה\"ב: תופעת ארלינג הולאנד\nארלינג הולאנד is seeing increased search interest in Israel.\nSource: Sport5.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "כאן 11 מונדיאל",
      slug: "il-כאן-11-מונדיאל-2026-07-11",
      traffic: "2000+",
      description: "נירו לוי נגד כאן 11: \"למה היה צריך לשלוח 200 איש?\"",
      source: "ice (אייס)",
      sourceUrl: "https://www.ice.co.il/media/news/article/1120419",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQjHv6urBQAWuu-VIdNyj9kTngXR9h7aR65bcFuoSUNDBbkQxIwzFBwz8iOWhg",
      country: "IL",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "כאן 11 מונדיאל",
        "כאן 11 מונדיאל news",
        "כאן 11 מונדיאל Israel"
      ],
      summary: "נירו לוי נגד כאן 11: \"למה היה צריך לשלוח 200 איש?\"",
      detail: "נירו לוי נגד כאן 11: \"למה היה צריך לשלוח 200 איש?\"\nכאן 11 מונדיאל is seeing increased search interest in Israel.\nSource: ice (אייס).\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AE: [
    {
      title: "مباراة اليوم",
      slug: "ae-مباراة-اليوم-2026-07-11",
      traffic: "200+",
      description: "موقف \"محرج\" لحكم مباراة إسبانيا وبلجيكا.. هذا ما حدث معه",
      source: "CNN Arabic",
      sourceUrl: "https://arabic.cnn.com/sport/article/2026/07/11/referee-belgium-spain-match",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRotCzhTzKceW2bN5uuYXzMMktDIqi8o06KuWOYPXgq5ImY-SqrCwvJp07MaqE",
      country: "AE",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "مباراة اليوم",
        "مباراة اليوم news",
        "مباراة اليوم UAE"
      ],
      summary: "موقف \"محرج\" لحكم مباراة إسبانيا وبلجيكا.. هذا ما حدث معه",
      detail: "موقف \"محرج\" لحكم مباراة إسبانيا وبلجيكا.. هذا ما حدث معه\nمباراة اليوم is seeing increased search interest in UAE.\nSource: CNN Arabic.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  NZ: [
    {
      title: "braut haaland",
      slug: "nz-braut-haaland-2026-07-11",
      traffic: "100+",
      description: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      source: "ESPN",
      sourceUrl: "https://www.espn.com/soccer/story/_/id/49316632/erling-haaland-norway-world-cup-manchester-city-england-striker-analysis-lionel-messi",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo3UWS8lySMZ3OehFp0S7dZaQWY9ZV_SxuYSiKq0YrrxIkeTknkp7qDQIKV8g",
      country: "NZ",
      date: "2026-07-11",
      pubTime: "35m ago",
      relatedQueries: [
        "braut haaland",
        "braut haaland news",
        "braut haaland New Zealand"
      ],
      summary: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      detail: "Forget Messi & Co., because this is Erling Haaland's World Cup\nbraut haaland is seeing increased search interest in New Zealand.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jordan pickford",
      slug: "nz-jordan-pickford-2026-07-11",
      traffic: "100+",
      description: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/cj9gknxm91vo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSr4rFPxASmFh5_-huGzZ6Q1YrUyCY5qFpYSGdovGM47MoO7tw8arIe6s0Jtzo",
      country: "NZ",
      date: "2026-07-11",
      pubTime: "45m ago",
      relatedQueries: [
        "jordan pickford",
        "jordan pickford news",
        "jordan pickford New Zealand"
      ],
      summary: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      detail: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves\njordan pickford is seeing increased search interest in New Zealand.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "declan rice",
      slug: "nz-declan-rice-2026-07-11",
      traffic: "100+",
      description: "World Cup 2026: England team news - Stones set to start against Norway",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c7vyp994jjgo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQUh86MG_-MAdVnCWczFWPt_-sjjufW5zcXcRt4gigMMH6I88_vIkfcCd_Nde8",
      country: "NZ",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "declan rice",
        "declan rice news",
        "declan rice New Zealand"
      ],
      summary: "World Cup 2026: England team news - Stones set to start against Norway",
      detail: "World Cup 2026: England team news - Stones set to start against Norway\ndeclan rice is seeing increased search interest in New Zealand.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "haaland height",
      slug: "nz-haaland-height-2026-07-11",
      traffic: "100+",
      description: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      source: "ESPN",
      sourceUrl: "https://www.espn.com/soccer/story/_/id/49316632/erling-haaland-norway-world-cup-manchester-city-england-striker-analysis-lionel-messi",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILSZdqYAR1NUzqgOF5xGBqNRKvbZow8fH2Z3g9T8kLBIsra-Yg_tx0S0Pa-8",
      country: "NZ",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "haaland height",
        "haaland height news",
        "haaland height New Zealand"
      ],
      summary: "Forget Messi & Co., because this is Erling Haaland's World Cup",
      detail: "Forget Messi & Co., because this is Erling Haaland's World Cup\nhaaland height is seeing increased search interest in New Zealand.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "erling haaland",
      slug: "nz-erling-haaland-2026-07-11",
      traffic: "1000+",
      description: "Erling Haaland’s ‘doppelganger’ Emma Kate Willman breaks silence on their ‘unreal’ resemblance",
      source: "NZ Herald",
      sourceUrl: "https://www.nzherald.co.nz/entertainment/erling-haalands-doppelganger-emma-kate-willman-breaks-silence-on-their-unreal-resemblance/SSTM6KLAJJEIJOTGNIZAH222RQ/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3ygghiVN8kjqvlAnpvM2vhmFk0FgoA5T58J9BJpsqCHj8cUHr16wcH4dyznc",
      country: "NZ",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "erling haaland",
        "erling haaland news",
        "erling haaland New Zealand"
      ],
      summary: "Erling Haaland’s ‘doppelganger’ Emma Kate Willman breaks silence on their ‘unreal’ resemblance",
      detail: "Erling Haaland’s ‘doppelganger’ Emma Kate Willman breaks silence on their ‘unreal’ resemblance\nerling haaland is seeing increased search interest in New Zealand.\nSource: NZ Herald.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  FI: [
    {
      title: "declan rice",
      slug: "fi-declan-rice-2026-07-11",
      traffic: "200+",
      description: "World Cup 2026: England team news - Stones set to start against Norway",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c7vyp994jjgo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQUh86MG_-MAdVnCWczFWPt_-sjjufW5zcXcRt4gigMMH6I88_vIkfcCd_Nde8",
      country: "FI",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "declan rice",
        "declan rice news",
        "declan rice Finland"
      ],
      summary: "World Cup 2026: England team news - Stones set to start against Norway",
      detail: "World Cup 2026: England team news - Stones set to start against Norway\ndeclan rice is seeing increased search interest in Finland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "fifa",
      slug: "fi-fifa-2026-07-11",
      traffic: "500+",
      description: "Mitä ihmettä Messi tekee MM-kentillä? Tilasto hätkähdyttää",
      source: "Iltalehti",
      sourceUrl: "https://www.iltalehti.fi/jalkapallon-mm-2026/a/a0df5fbe-1ce8-4be6-bcc9-00dcf89a7eaa",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRM7VDZaARpEodfFuyv7ZatiPCgfRZtApwH05sgQdDUyWb5hYKGXRQ23zJZSek",
      country: "FI",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "fifa",
        "fifa news",
        "fifa Finland"
      ],
      summary: "Mitä ihmettä Messi tekee MM-kentillä? Tilasto hätkähdyttää",
      detail: "Mitä ihmettä Messi tekee MM-kentillä? Tilasto hätkähdyttää\nfifa is seeing increased search interest in Finland.\nSource: Iltalehti.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  TW: [
    {
      title: "許淑華",
      slug: "tw-許淑華-2026-07-11",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "TW",
      date: "2026-07-11",
      pubTime: "35m ago",
      relatedQueries: [
        "許淑華",
        "許淑華 news",
        "許淑華 Taiwan"
      ],
      summary: "許淑華 is trending in Taiwan.",
      detail: "許淑華 is trending in Taiwan.\n許淑華 is seeing increased search interest in Taiwan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "體育",
      slug: "tw-體育-2026-07-11",
      traffic: "100+",
      description: "批李洋改革後道歉運彩公會理事長發聲明退出經營| 運動",
      source: "中央社 CNA",
      sourceUrl: "https://www.cna.com.tw/news/aspt/202607080076.aspx",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl5UnSWNF2nytJW3r9WWHIdVAVfeMnN2_bpwRMbPA3Xfbr9mqTllQdrMddjpE",
      country: "TW",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "體育",
        "體育 news",
        "體育 Taiwan"
      ],
      summary: "批李洋改革後道歉運彩公會理事長發聲明退出經營| 運動",
      detail: "批李洋改革後道歉運彩公會理事長發聲明退出經營| 運動\n體育 is seeing increased search interest in Taiwan.\nSource: 中央社 CNA.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "世界杯2026",
      slug: "tw-世界杯2026-2026-07-11",
      traffic: "200+",
      description: "世界杯2026：什么是VAR？为何在世界杯具有争议性？",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/zhongwen/articles/ckg8x01k1j9o/simp",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN0Z2MDdK1CHaIvKP8aBDkLQ3R5nFXWFFOPRJSl1ipJSATW79VFmJM1r41a94",
      country: "TW",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "世界杯2026",
        "世界杯2026 news",
        "世界杯2026 Taiwan"
      ],
      summary: "世界杯2026：什么是VAR？为何在世界杯具有争议性？",
      detail: "世界杯2026：什么是VAR？为何在世界杯具有争议性？\n世界杯2026 is seeing increased search interest in Taiwan.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  SA: [
    {
      title: "norway national football team vs england national football team lineups",
      slug: "sa-norway-national-football-team-vs-england-national-football-team-lineups-2026-07-11",
      traffic: "1000+",
      description: "World Cup 2026: England team news - Stones set to start against Norway",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c7vyp994jjgo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQUh86MG_-MAdVnCWczFWPt_-sjjufW5zcXcRt4gigMMH6I88_vIkfcCd_Nde8",
      country: "SA",
      date: "2026-07-11",
      pubTime: "55m ago",
      relatedQueries: [
        "norway national football team vs england national football team lineups",
        "norway national football team vs england national football team lineups news",
        "norway national football team vs england national football team lineups Saudi Arabia"
      ],
      summary: "World Cup 2026: England team news - Stones set to start against Norway",
      detail: "World Cup 2026: England team news - Stones set to start against Norway\nnorway national football team vs england national football team lineups is seeing increased search interest in Saudi Arabia.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jordan pickford",
      slug: "sa-jordan-pickford-2026-07-11",
      traffic: "100+",
      description: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/cj9gknxm91vo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSr4rFPxASmFh5_-huGzZ6Q1YrUyCY5qFpYSGdovGM47MoO7tw8arIe6s0Jtzo",
      country: "SA",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "jordan pickford",
        "jordan pickford news",
        "jordan pickford Saudi Arabia"
      ],
      summary: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves",
      detail: "World Cup 2026: Jordan Pickford - Time to finally give England goalkeeper credit he deserves\njordan pickford is seeing increased search interest in Saudi Arabia.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ألكسندر سورلوث",
      slug: "sa-ألكسندر-سورلوث-2026-07-11",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "SA",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "ألكسندر سورلوث",
        "ألكسندر سورلوث news",
        "ألكسندر سورلوث Saudi Arabia"
      ],
      summary: "ألكسندر سورلوث is trending in Saudi Arabia.",
      detail: "ألكسندر سورلوث is trending in Saudi Arabia.\nألكسندر سورلوث is seeing increased search interest in Saudi Arabia.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "andreas schjelderup",
      slug: "sa-andreas-schjelderup-2026-07-11",
      traffic: "10000+",
      description: "England vs Norway LIVE: Watch World Cup 2026 quarter-final stream, score, commentary & updates",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/live/cgl33l55100t",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkz1EocJfArvtdoxzvO1yUQy-qqMYAU6U8maFroTWp5CSV1buXpt72Z8rQk2k",
      country: "SA",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "andreas schjelderup",
        "andreas schjelderup news",
        "andreas schjelderup Saudi Arabia"
      ],
      summary: "England vs Norway LIVE: Watch World Cup 2026 quarter-final stream, score, commentary & updates",
      detail: "England vs Norway LIVE: Watch World Cup 2026 quarter-final stream, score, commentary & updates\nandreas schjelderup is seeing increased search interest in Saudi Arabia.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  HK: [
    {
      title: "fifa",
      slug: "hk-fifa-2026-07-11",
      traffic: "500+",
      description: "World Cup 2026: Fifa official refuses to answer ban questions from BBC",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c4gy1j87e1yo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQW1BRdaWHCE3CWSzTEVfLQlBUr5eW6MnS3nj9FcQSPgJzW--Zq6oskHoH45gE",
      country: "HK",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "fifa",
        "fifa news",
        "fifa Hong Kong"
      ],
      summary: "World Cup 2026: Fifa official refuses to answer ban questions from BBC",
      detail: "World Cup 2026: Fifa official refuses to answer ban questions from BBC\nfifa is seeing increased search interest in Hong Kong.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "declan rice",
      slug: "hk-declan-rice-2026-07-11",
      traffic: "200+",
      description: "World Cup 2026: England team news - Stones set to start against Norway",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/c7vyp994jjgo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQUh86MG_-MAdVnCWczFWPt_-sjjufW5zcXcRt4gigMMH6I88_vIkfcCd_Nde8",
      country: "HK",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "declan rice",
        "declan rice news",
        "declan rice Hong Kong"
      ],
      summary: "World Cup 2026: England team news - Stones set to start against Norway",
      detail: "World Cup 2026: England team news - Stones set to start against Norway\ndeclan rice is seeing increased search interest in Hong Kong.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "埃茲里·孔薩",
      slug: "hk-埃茲里孔薩-2026-07-11",
      traffic: "200+",
      description: "世界杯｜对挪威前夕英格兰三将复操",
      source: "香港電台",
      sourceUrl: "https://gbcode.rthk.hk/TuniS/news.rthk.hk/rthk/ch/component/k2/1861868-20260711.htm",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRltz-qZBQJqC9r_HV8pzipZ9b2Y-cvthmZJ3iZ03bH_hFSveaAirQTMkm1pKE",
      country: "HK",
      date: "2026-07-11",
      pubTime: "1h ago",
      relatedQueries: [
        "埃茲里·孔薩",
        "埃茲里·孔薩 news",
        "埃茲里·孔薩 Hong Kong"
      ],
      summary: "世界杯｜对挪威前夕英格兰三将复操",
      detail: "世界杯｜对挪威前夕英格兰三将复操\n埃茲里·孔薩 is seeing increased search interest in Hong Kong.\nSource: 香港電台.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ]
};

export function getPreloadedTrends(countryCode: string): TrendItem[] {
  return preloadedTrends[countryCode] || [];
}
