// Auto-generated by update-trends.mjs
// Last updated: 2026-06-04T23:36:59.989Z
// DO NOT EDIT MANUALLY - this file is overwritten every 30 minutes

import { TrendItem } from "@/lib/google-trends";

const today = new Date().toISOString().split("T")[0];

export const preloadedTrends: Record<string, TrendItem[]> = {
  US: [
    {
      title: "ellen pompeo next tv role",
      slug: "us-ellen-pompeo-next-tv-role-2026-06-04",
      traffic: "500+",
      description: "Ellen Pompeo Stars In Dramedy Pilot ‘Chicks’ Ordered By Hulu From ‘Good American Family’ Creator Katie Robbins",
      source: "Deadline",
      sourceUrl: "https://deadline.com/2026/06/ellen-pompeo-pilot-chicks-ordered-hulu-1236940901/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR4-lUSAA1sJ7HxblBgIjpHO2ndf3q5yLQnWYcQ0Wl3ZmrWkKj6Eytra6rBjEc",
      country: "US",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "ellen pompeo next tv role",
        "ellen pompeo next tv role news",
        "ellen pompeo next tv role United States"
      ],
      summary: "Ellen Pompeo Stars In Dramedy Pilot ‘Chicks’ Ordered By Hulu From ‘Good American Family’ Creator Katie Robbins",
      detail: "Ellen Pompeo Stars In Dramedy Pilot ‘Chicks’ Ordered By Hulu From ‘Good American Family’ Creator Katie Robbins\nellen pompeo next tv role is seeing increased search interest in United States.\nSource: Deadline.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "soap opera digest",
      slug: "us-soap-opera-digest-2026-06-04",
      traffic: "500+",
      description: "GH Comings & Goings: It's The End of the Road for One Villain",
      source: "Soap Opera Digest",
      sourceUrl: "https://www.soapoperadigest.com/content/general-hospital-comings-goings-its-the-end-of-the-road-for-one-villain/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSTD-f5YK2GkTLQwxSFgu0oz2NAxZyIBWQJQ3On1TkeSGDLs6WZGwg1ip9Nf9M",
      country: "US",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "soap opera digest",
        "soap opera digest news",
        "soap opera digest United States"
      ],
      summary: "GH Comings & Goings: It's The End of the Road for One Villain",
      detail: "GH Comings & Goings: It's The End of the Road for One Villain\nsoap opera digest is seeing increased search interest in United States.\nSource: Soap Opera Digest.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "chequia - guatemala",
      slug: "us-chequia-guatemala-2026-06-04",
      traffic: "5000+",
      description: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara",
      source: "ESPN Deportes",
      sourceUrl: "https://espndeportes.espn.com/futbol/guatemala/nota/_/id/16795807/ausencia-rubio-rubin-nathaniel-mendez-laing-seleccion-guatemala-luis-fernando-tena",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ45nQR4jTRQhcStbFFa91a61m6WohzpO727-ROHiJByd1EFrzn7g9ExsyZ6ZA",
      country: "US",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "chequia - guatemala",
        "chequia - guatemala news",
        "chequia - guatemala United States"
      ],
      summary: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara",
      detail: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara\nchequia - guatemala is seeing increased search interest in United States.\nSource: ESPN Deportes.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jason statham",
      slug: "us-jason-statham-2026-06-04",
      traffic: "500+",
      description: "‘Jason Statham Stole My Bike’: Black Bear Dates Action Comedy For Late Summer 2027",
      source: "Deadline",
      sourceUrl: "https://deadline.com/2026/06/jason-statham-stole-my-bike-release-date-1236940958/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTWiIAwc5oZpRy5S7Bb0EJLjOxQ3ol5dCynV-Lk4mVsp9aLn6SRydXY_lwJat0",
      country: "US",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "jason statham",
        "jason statham news",
        "jason statham United States"
      ],
      summary: "‘Jason Statham Stole My Bike’: Black Bear Dates Action Comedy For Late Summer 2027",
      detail: "‘Jason Statham Stole My Bike’: Black Bear Dates Action Comedy For Late Summer 2027\njason statham is seeing increased search interest in United States.\nSource: Deadline.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "stella lefty",
      slug: "us-stella-lefty-2026-06-04",
      traffic: "500+",
      description: "Only two songs with ‘Boston’ in the title have charted on the Hot 100. Stella Lefty just added a third.",
      source: "The Boston Globe",
      sourceUrl: "https://www.bostonglobe.com/2026/06/03/arts/stella-lefty-boston-billboard-hot-100/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0ApsPiPeNTwfC0gyxy32giurxzr0-nQgytmPq9-2BZo8wBtWbWNx6UlsR38Y",
      country: "US",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "stella lefty",
        "stella lefty news",
        "stella lefty United States"
      ],
      summary: "Only two songs with ‘Boston’ in the title have charted on the Hot 100. Stella Lefty just added a third.",
      detail: "Only two songs with ‘Boston’ in the title have charted on the Hot 100. Stella Lefty just added a third.\nstella lefty is seeing increased search interest in United States.\nSource: The Boston Globe.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  GB: [
    {
      title: "taken",
      slug: "gb-taken-2026-06-04",
      traffic: "2000+",
      description: "Man shot with crossbow at the University of Surrey, say police",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/news/articles/cn4p4yllq1lo",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-9HtBCUQaHEq67ySgjhI4SI-swgOUH8vZu2LVthuIerA_f-LACi8GEd6yUQs",
      country: "GB",
      date: "2026-06-04",
      pubTime: "46m ago",
      relatedQueries: [
        "taken",
        "taken news",
        "taken United Kingdom"
      ],
      summary: "Man shot with crossbow at the University of Surrey, say police",
      detail: "Man shot with crossbow at the University of Surrey, say police\ntaken is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "vitinha",
      slug: "gb-vitinha-2026-06-04",
      traffic: "1000+",
      description: "Perez wants Vitinha, Barcola linked with move to England - Euro Transfer News",
      source: "TNT Sports",
      sourceUrl: "https://www.tntsports.co.uk/football/transfers/2025-2026/florentino-perez-paris-saint-germain-star-vitinha-bradley-barcola-england-move-euro-transfer-news_sto23306502/story.shtml",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRymk-JttClbkLmtr963KwIRTDXsilvxF-FUWMt_adIUhEx2Nr1cF4McIwtOmg",
      country: "GB",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "vitinha",
        "vitinha news",
        "vitinha United Kingdom"
      ],
      summary: "Perez wants Vitinha, Barcola linked with move to England - Euro Transfer News",
      detail: "Perez wants Vitinha, Barcola linked with move to England - Euro Transfer News\nvitinha is seeing increased search interest in United Kingdom.\nSource: TNT Sports.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "joao neves",
      slug: "gb-joao-neves-2026-06-04",
      traffic: "500+",
      description: "Real Madrid's Florentino Pérez: I'll announce 'first big signing' on Thursday",
      source: "ESPN",
      sourceUrl: "https://www.espn.co.uk/football/story/_/id/48954899/florentino-perez-ill-announce-first-big-signing-thursday",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTOPP7RqaLa1yMkFqzVKDHmFFsRpjRgaRBGUT3w5O-3A7t2kGqhhipWzG23CHI",
      country: "GB",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "joao neves",
        "joao neves news",
        "joao neves United Kingdom"
      ],
      summary: "Real Madrid's Florentino Pérez: I'll announce 'first big signing' on Thursday",
      detail: "Real Madrid's Florentino Pérez: I'll announce 'first big signing' on Thursday\njoao neves is seeing increased search interest in United Kingdom.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "anthropic",
      slug: "gb-anthropic-2026-06-04",
      traffic: "1000+",
      description: "AI needs a 'brake pedal', warns Anthropic co-founder",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/news/articles/cx2124z7g45o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT_mdc5ykxm249wRG_vwUcR1R34b9omgfVx7u49u3ENaGYkNWmGTq8KNkHGPuQ",
      country: "GB",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "anthropic",
        "anthropic news",
        "anthropic United Kingdom"
      ],
      summary: "AI needs a 'brake pedal', warns Anthropic co-founder",
      detail: "AI needs a 'brake pedal', warns Anthropic co-founder\nanthropic is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "charles leclerc",
      slug: "gb-charles-leclerc-2026-06-04",
      traffic: "200+",
      description: "Charles Leclerc: Ferrari driver signs long-term contract",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/sport/formula1/articles/cy02xy2815yo",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR_5XtYWZfYYkIH81Js9crubDFhvsUygn1vszVATAi1pE0Sd0New8diDPZBcjg",
      country: "GB",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "charles leclerc",
        "charles leclerc news",
        "charles leclerc United Kingdom"
      ],
      summary: "Charles Leclerc: Ferrari driver signs long-term contract",
      detail: "Charles Leclerc: Ferrari driver signs long-term contract\ncharles leclerc is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  JP: [
    {
      title: "賀来賢人 奥さん",
      slug: "jp-賀来賢人-奥さん-2026-06-04",
      traffic: "2000+",
      description: "「家に榮倉奈々いるのずるくない？」賀来賢人、自宅での妻・榮倉奈々を公開！「案外庶民的でかわいい」",
      source: "ｄメニューニュース",
      sourceUrl: "https://topics.smt.docomo.ne.jp/article/allaboutnews/entertainment/allaboutnews-156917",
      imageUrl: "",
      country: "JP",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "賀来賢人 奥さん",
        "賀来賢人 奥さん news",
        "賀来賢人 奥さん Japan"
      ],
      summary: "「家に榮倉奈々いるのずるくない？」賀来賢人、自宅での妻・榮倉奈々を公開！「案外庶民的でかわいい」",
      detail: "「家に榮倉奈々いるのずるくない？」賀来賢人、自宅での妻・榮倉奈々を公開！「案外庶民的でかわいい」\n賀来賢人 奥さん is seeing increased search interest in Japan.\nSource: ｄメニューニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "舘ひろし",
      slug: "jp-舘ひろし-2026-06-04",
      traffic: "5000+",
      description: "プレスリリース：シェアサイクルサービス『チャリチャリ』、映画『免許返納!?』とのタイアップによる、父の日プレゼントキャンペーンを実施（PR TIMES）",
      source: "毎日新聞",
      sourceUrl: "https://mainichi.jp/articles/20260603/pr2/00m/020/198000c",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTy87b6v3CRkq4YzTtU_hhK61EJKyGDnM9Y0Y9tlhaQEeI5vM0BoDRenJWxMq0",
      country: "JP",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "舘ひろし",
        "舘ひろし news",
        "舘ひろし Japan"
      ],
      summary: "プレスリリース：シェアサイクルサービス『チャリチャリ』、映画『免許返納!?』とのタイアップによる、父の日プレゼントキャンペーンを実施（PR TIMES）",
      detail: "プレスリリース：シェアサイクルサービス『チャリチャリ』、映画『免許返納!?』とのタイアップによる、父の日プレゼントキャンペーンを実施（PR TIMES）\n舘ひろし is seeing increased search interest in Japan.\nSource: 毎日新聞.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "トヨタ自動車",
      slug: "jp-トヨタ自動車-2026-06-04",
      traffic: "200+",
      description: "トヨタ「新型アルファード」発表に反響殺到！ さらなる新グレード投入で「新型エルグラに合わせてきた」「容赦ないな」の声も！ キング・オブ“高級ミニバン”一部改良に寄せられた“熱視線”とは",
      source: "ｄメニューニュース",
      sourceUrl: "https://topics.smt.docomo.ne.jp/article/kurumanews/trend/kurumanews-1068777?page=4",
      imageUrl: "",
      country: "JP",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "トヨタ自動車",
        "トヨタ自動車 news",
        "トヨタ自動車 Japan"
      ],
      summary: "トヨタ「新型アルファード」発表に反響殺到！ さらなる新グレード投入で「新型エルグラに合わせてきた」「容赦ないな」の声も！ キング・オブ“高級ミニバン”一部改良に寄せられた“熱視線”とは",
      detail: "トヨタ「新型アルファード」発表に反響殺到！ さらなる新グレード投入で「新型エルグラに合わせてきた」「容赦ないな」の声も！ キング・オブ“高級ミニバン”一部改良に寄せられた“熱視線”とは\nトヨタ自動車 is seeing increased search interest in Japan.\nSource: ｄメニューニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ブレーブス 対 ブルージェイズ",
      slug: "jp-ブレーブス-対-ブルージェイズ-2026-06-04",
      traffic: "2000+",
      description: "【ＭＬＢ】岡本和真に追い風 ４連敗のブルージェイズが早期補強で逆転ＰＯへ前のめり＝海外報道（東スポWEB）",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/ce2d0ca93c9f6661fd32cf77ac425708464a772c",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRWPCF0UfKXJo9WP7QhHHe168rNiH04nhFHrw_RQvdQCI09bQUatDX5s-Rm6-I",
      country: "JP",
      date: "2026-06-04",
      pubTime: "36m ago",
      relatedQueries: [
        "ブレーブス 対 ブルージェイズ",
        "ブレーブス 対 ブルージェイズ news",
        "ブレーブス 対 ブルージェイズ Japan"
      ],
      summary: "【ＭＬＢ】岡本和真に追い風 ４連敗のブルージェイズが早期補強で逆転ＰＯへ前のめり＝海外報道（東スポWEB）",
      detail: "【ＭＬＢ】岡本和真に追い風 ４連敗のブルージェイズが早期補強で逆転ＰＯへ前のめり＝海外報道（東スポWEB）\nブレーブス 対 ブルージェイズ is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ラセンウジバエ",
      slug: "jp-ラセンウジバエ-2026-06-04",
      traffic: "200+",
      description: "肉食バエが米テキサス州で発生 家畜に寄生、まん延なら牛肉高騰",
      source: "日本経済新聞",
      sourceUrl: "https://www.nikkei.com/article/DGXZQOGN04D3E0U6A600C2000000/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQHOZYwte-6gAJABKM8O3oA1jEIAN2BLOfwcNpfseDIgbOLX4nOx02OAlv1jYo",
      country: "JP",
      date: "2026-06-04",
      pubTime: "36m ago",
      relatedQueries: [
        "ラセンウジバエ",
        "ラセンウジバエ news",
        "ラセンウジバエ Japan"
      ],
      summary: "肉食バエが米テキサス州で発生 家畜に寄生、まん延なら牛肉高騰",
      detail: "肉食バエが米テキサス州で発生 家畜に寄生、まん延なら牛肉高騰\nラセンウジバエ is seeing increased search interest in Japan.\nSource: 日本経済新聞.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  CA: [
    {
      title: "alouettes vs tiger-cats",
      slug: "ca-alouettes-vs-tiger-cats-2026-06-04",
      traffic: "200+",
      description: "Week 1: Montreal Alouettes at Hamilton Tiger-Cats",
      source: "CFL.ca",
      sourceUrl: "https://www.cfl.ca/2026/06/01/week-1-montreal-alouettes-at-hamilton-tiger-cats/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTLoT5aMZGHm5TFhoQQN6ryQqX0jZrt9Pl01f8id9bsbTJF1kOkTbCQOHzZSlw",
      country: "CA",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "alouettes vs tiger-cats",
        "alouettes vs tiger-cats news",
        "alouettes vs tiger-cats Canada"
      ],
      summary: "Week 1: Montreal Alouettes at Hamilton Tiger-Cats",
      detail: "Week 1: Montreal Alouettes at Hamilton Tiger-Cats\nalouettes vs tiger-cats is seeing increased search interest in Canada.\nSource: CFL.ca.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "perquisition",
      slug: "ca-perquisition-2026-06-04",
      traffic: "200+",
      description: "Perquisition importante de stupéfiants : 300 000 $ saisis",
      source: "TVA - CIMT-CHAU",
      sourceUrl: "https://cimtchau.ca/nouvelles/perquisition-importante-de-stupefiants-300-000-saisis/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPpIPrRRuos_NYmkNoYULINF9cH7Kpl6f3lO9MipP1lfqu-bPCcnREkXaXOrI",
      country: "CA",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "perquisition",
        "perquisition news",
        "perquisition Canada"
      ],
      summary: "Perquisition importante de stupéfiants : 300 000 $ saisis",
      detail: "Perquisition importante de stupéfiants : 300 000 $ saisis\nperquisition is seeing increased search interest in Canada.\nSource: TVA - CIMT-CHAU.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "chris sale",
      slug: "ca-chris-sale-2026-06-04",
      traffic: "500+",
      description: "Why you should lean Blue Jays behind Gausman in series opener vs. Braves",
      source: "Sportsnet",
      sourceUrl: "https://www.sportsnet.ca/mlb/video/why-you-should-lean-blue-jays-behind-gausman-in-series-opener-vs-braves/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQk-OHBBSFUtTGuRbPfFg_sf5d5wU_xWJq5osyO2dZmxLYfifjzLap6cO5IvZ8",
      country: "CA",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "chris sale",
        "chris sale news",
        "chris sale Canada"
      ],
      summary: "Why you should lean Blue Jays behind Gausman in series opener vs. Braves",
      detail: "Why you should lean Blue Jays behind Gausman in series opener vs. Braves\nchris sale is seeing increased search interest in Canada.\nSource: Sportsnet.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "united airlines",
      slug: "ca-united-airlines-2026-06-04",
      traffic: "200+",
      description: "United Airlines flight was 19 feet above highway when it struck a pole, NTSB says",
      source: "CNN",
      sourceUrl: "https://www.cnn.com/2026/06/04/us/united-airlines-newark-nj-ntsb",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQPai5Evp083y7Q9CdFUPYa4Z93v0Zim0PTS72p0PQC9Z0g6UAg4tKGSehij2E",
      country: "CA",
      date: "2026-06-04",
      pubTime: "36m ago",
      relatedQueries: [
        "united airlines",
        "united airlines news",
        "united airlines Canada"
      ],
      summary: "United Airlines flight was 19 feet above highway when it struck a pole, NTSB says",
      detail: "United Airlines flight was 19 feet above highway when it struck a pole, NTSB says\nunited airlines is seeing increased search interest in Canada.\nSource: CNN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "alexis lafrenière",
      slug: "ca-alexis-lafrenire-2026-06-04",
      traffic: "500+",
      description: "Alexis Lafrenière in Montreal: Frank Seravalli reveals what the trade might have looked like",
      source: "Dose.ca",
      sourceUrl: "https://dose.ca/2026/06/04/alexis-lafreniere-in-montreal-frank-seravalli-reveals-what-the-trade-might-have-looked-like/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTyrCfPbhjtNVqOd7Noz4kxP3_Ee2Y1VR6gm9qXB9PH5h5VVn63PuxnB42QzfI",
      country: "CA",
      date: "2026-06-04",
      pubTime: "46m ago",
      relatedQueries: [
        "alexis lafrenière",
        "alexis lafrenière news",
        "alexis lafrenière Canada"
      ],
      summary: "Alexis Lafrenière in Montreal: Frank Seravalli reveals what the trade might have looked like",
      detail: "Alexis Lafrenière in Montreal: Frank Seravalli reveals what the trade might have looked like\nalexis lafrenière is seeing increased search interest in Canada.\nSource: Dose.ca.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AU: [
    {
      title: "clint stanaway",
      slug: "au-clint-stanaway-2026-06-04",
      traffic: "500+",
      description: "'Powerful': Daniher family speaks to Demons, Magpies",
      source: "afl.com.au",
      sourceUrl: "https://www.afl.com.au/news/1533112/powerful-daniher-family-speaks-to-melbourne-demons-collingwood-magpies",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSrPzRi-AarYG7gpzN9cAtozcQLXzsoRR32dxEHJZEWsKcJLTIdpRXqi5Q3DrM",
      country: "AU",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "clint stanaway",
        "clint stanaway news",
        "clint stanaway Australia"
      ],
      summary: "'Powerful': Daniher family speaks to Demons, Magpies",
      detail: "'Powerful': Daniher family speaks to Demons, Magpies\nclint stanaway is seeing increased search interest in Australia.\nSource: afl.com.au.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "australia federal budget cgt changes",
      slug: "au-australia-federal-budget-cgt-changes-2026-06-04",
      traffic: "200+",
      description: "Australia's lower house passes bill for biggest overhaul of taxes in decades",
      source: "Reuters",
      sourceUrl: "https://www.reuters.com/legal/transactional/australias-lower-house-passes-bill-biggest-overhaul-taxes-decades-2026-06-04/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoI3KiNv65OuKvF1rX3V2yAouJoRkEIi5mbBaUXszc5Vp_to5VTdp3BE5bxcM",
      country: "AU",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "australia federal budget cgt changes",
        "australia federal budget cgt changes news",
        "australia federal budget cgt changes Australia"
      ],
      summary: "Australia's lower house passes bill for biggest overhaul of taxes in decades",
      detail: "Australia's lower house passes bill for biggest overhaul of taxes in decades\naustralia federal budget cgt changes is seeing increased search interest in Australia.\nSource: Reuters.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "dow jones industrial average",
      slug: "au-dow-jones-industrial-average-2026-06-04",
      traffic: "100+",
      description: "Morning Wrap: ASX 200 to rise, Dow hits record as Broadcom rocks the AI trade",
      source: "Market Index",
      sourceUrl: "https://www.marketindex.com.au/news/morning-wrap-asx-200-to-rise-dow-hits-record-as-broadcom-rocks-the-ai-trade",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRQd7BZuoTqd85GVgdvU97kacYxn7IO3oZVB-r7elNTsURKNCYE6XBMyKl5qXk",
      country: "AU",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "dow jones industrial average",
        "dow jones industrial average news",
        "dow jones industrial average Australia"
      ],
      summary: "Morning Wrap: ASX 200 to rise, Dow hits record as Broadcom rocks the AI trade",
      detail: "Morning Wrap: ASX 200 to rise, Dow hits record as Broadcom rocks the AI trade\ndow jones industrial average is seeing increased search interest in Australia.\nSource: Market Index.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "oscar",
      slug: "au-oscar-2026-06-04",
      traffic: "500+",
      description: "‘Couldn’t handle pressure’: Former champ’s rogue Piastri whack",
      source: "Nine.com.au",
      sourceUrl: "https://www.nine.com.au/sport/motorsport/formula-1/f1-news-2026-oscar-piastri-criticised-kimi-raikkonen-interview-20260603-p603eh.html",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS7aQrsS67p9CF4GqjDP00a0BKBK0k5MrmXYpvVRLtisC9h2Bc1j9vNna3AX4A",
      country: "AU",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "oscar",
        "oscar news",
        "oscar Australia"
      ],
      summary: "‘Couldn’t handle pressure’: Former champ’s rogue Piastri whack",
      detail: "‘Couldn’t handle pressure’: Former champ’s rogue Piastri whack\noscar is seeing increased search interest in Australia.\nSource: Nine.com.au.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  FR: [
    {
      title: "christian negre",
      slug: "fr-christian-negre-2026-06-04",
      traffic: "500+",
      description: "Cinq femmes demandent la condamnation de l’Etat pour inaction face à Christian Nègre, un ancien haut fonctionnaire qui les droguait pour les forcer à uriner devant lui",
      source: "Le Monde.fr",
      sourceUrl: "https://www.lemonde.fr/societe/article/2026/06/04/cinq-femmes-demandent-la-condamnation-de-l-etat-pour-inaction-face-a-un-ancien-haut-fonctionnaire-qui-les-droguait-pour-les-forcer-a-uriner-devant-lui_6697504_3224.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTey92h_dtrjkdAdfX110jlyJRp5qvs_zrokhh9AW8ogWj1Ea3yHfrTLa_6L7U",
      country: "FR",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "christian negre",
        "christian negre news",
        "christian negre France"
      ],
      summary: "Cinq femmes demandent la condamnation de l’Etat pour inaction face à Christian Nègre, un ancien haut fonctionnaire qui les droguait pour les forcer à uriner devant lui",
      detail: "Cinq femmes demandent la condamnation de l’Etat pour inaction face à Christian Nègre, un ancien haut fonctionnaire qui les droguait pour les forcer à uriner devant lui\nchristian negre is seeing increased search interest in France.\nSource: Le Monde.fr.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "kylian mbappé",
      slug: "fr-kylian-mbapp-2026-06-04",
      traffic: "5000+",
      description: "Chambreur, déjà à fond à l'entraînement et en première ligne pour défendre ses coéquipiers, Kylian Mbappé déjà en mode leader avec les Bleus",
      source: "L'Équipe",
      sourceUrl: "https://www.lequipe.fr/Football/Article/Chambreur-deja-a-fond-a-l-entrainement-et-en-premiere-ligne-pour-defendre-ses-coequipiers-kylian-mbappe-deja-en-mode-leader-avec-les-bleus/1681555",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQVT4pcuCf14dYqkvDp90_Hs1bXUvf9cNY_2fp5UaUr89y3lvlnOoWOA0pbEak",
      country: "FR",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "kylian mbappé",
        "kylian mbappé news",
        "kylian mbappé France"
      ],
      summary: "Chambreur, déjà à fond à l'entraînement et en première ligne pour défendre ses coéquipiers, Kylian Mbappé déjà en mode leader avec les Bleus",
      detail: "Chambreur, déjà à fond à l'entraînement et en première ligne pour défendre ses coéquipiers, Kylian Mbappé déjà en mode leader avec les Bleus\nkylian mbappé is seeing increased search interest in France.\nSource: L'Équipe.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "classement fifa 2026",
      slug: "fr-classement-fifa-2026-2026-06-04",
      traffic: "1000+",
      description: "Une valeur marchande de plus de 350 millions d'euros : Lamine Yamal joueur le plus cher du monde, deux Français dans le top 5",
      source: "L'Équipe",
      sourceUrl: "https://www.lequipe.fr/Football/Actualites/Une-valeur-marchande-de-plus-de-350-millions-d-euros-lamine-yamal-joueur-le-plus-cher-du-monde-deux-francais-dans-le-top-5/1681381",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ5dsKl_cxveIEci3b_laRaIA2KQ6EoXU3RBcbR7Ak-iBi3dXvO7ujaPskDDNM",
      country: "FR",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "classement fifa 2026",
        "classement fifa 2026 news",
        "classement fifa 2026 France"
      ],
      summary: "Une valeur marchande de plus de 350 millions d'euros : Lamine Yamal joueur le plus cher du monde, deux Français dans le top 5",
      detail: "Une valeur marchande de plus de 350 millions d'euros : Lamine Yamal joueur le plus cher du monde, deux Français dans le top 5\nclassement fifa 2026 is seeing increased search interest in France.\nSource: L'Équipe.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "haakon de norvège",
      slug: "fr-haakon-de-norvge-2026-06-04",
      traffic: "500+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "FR",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "haakon de norvège",
        "haakon de norvège news",
        "haakon de norvège France"
      ],
      summary: "haakon de norvège is trending in France.",
      detail: "haakon de norvège is trending in France.\nhaakon de norvège is seeing increased search interest in France.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "balagne",
      slug: "fr-balagne-2026-06-04",
      traffic: "500+",
      description: "“Meurtre en Balagne” : malgré la Corse, un téléfilm toujours aussi formaté",
      source: "Télérama",
      sourceUrl: "https://www.telerama.fr/television/meurtre-en-balagne-malgre-la-corse-un-telefilm-toujours-aussi-formate_cri-7044550.php",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNsm27zn9lVTthBVYi4HXlR9Dg_gxEUe_jtwFR80e8lVy2VJ_M_HQv-vrhnck",
      country: "FR",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "balagne",
        "balagne news",
        "balagne France"
      ],
      summary: "“Meurtre en Balagne” : malgré la Corse, un téléfilm toujours aussi formaté",
      detail: "“Meurtre en Balagne” : malgré la Corse, un téléfilm toujours aussi formaté\nbalagne is seeing increased search interest in France.\nSource: Télérama.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  KR: [
    {
      title: "암",
      slug: "kr-암-2026-06-04",
      traffic: "2000+",
      description: "퓨쳐켐, 전립선암 진단제 'FC303' 유럽 판권 반환 합의",
      source: "아시아경제",
      sourceUrl: "https://www.asiae.co.kr/article/2026060508093561231",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Uailkedrox9iUsqLcqwoh-HNUlCsUfojotwNU7h_Z_JEPnBACMDEJtUSz94",
      country: "KR",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "암",
        "암 news",
        "암 South Korea"
      ],
      summary: "퓨쳐켐, 전립선암 진단제 'FC303' 유럽 판권 반환 합의",
      detail: "퓨쳐켐, 전립선암 진단제 'FC303' 유럽 판권 반환 합의\n암 is seeing increased search interest in South Korea.\nSource: 아시아경제.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "기은세",
      slug: "kr-기은세-2026-06-04",
      traffic: "500+",
      description: "기은세, 손 주름 시술 받았다…\"할머니 손 같다고 해서 스트레스\" (기은세)",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260605062116309",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTlfOvG979g6mZlcHL56Dj7v46qKNFt9u2t2ADbDGK4NdQIGMUtz54cySvp9og",
      country: "KR",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "기은세",
        "기은세 news",
        "기은세 South Korea"
      ],
      summary: "기은세, 손 주름 시술 받았다…\"할머니 손 같다고 해서 스트레스\" (기은세)",
      detail: "기은세, 손 주름 시술 받았다…\"할머니 손 같다고 해서 스트레스\" (기은세)\n기은세 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "이재갑",
      slug: "kr-이재갑-2026-06-04",
      traffic: "100+",
      description: "이재갑 안동시의원 당선인, 지방자치 사상 최초 ‘10선 기초의원’ 대기록 [6·3 지방선거 이후]",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260605060344074",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ2u6ZZcgnCjTJrLQPLfGii8wOnAc_8kj--3qa1QlhAOgdKoCcn6g05lNxx2TQ",
      country: "KR",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "이재갑",
        "이재갑 news",
        "이재갑 South Korea"
      ],
      summary: "이재갑 안동시의원 당선인, 지방자치 사상 최초 ‘10선 기초의원’ 대기록 [6·3 지방선거 이후]",
      detail: "이재갑 안동시의원 당선인, 지방자치 사상 최초 ‘10선 기초의원’ 대기록 [6·3 지방선거 이후]\n이재갑 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "이탁수",
      slug: "kr-이탁수-2026-06-04",
      traffic: "5000+",
      description: "'전희철 딸' 전수완, 미스코리아 본선 가더니…배우 뺨치는 비주얼",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260604154450029",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQJb7Vth3pPo2LgIkJiX1iX6mkIt_HjwVPcaghrivTRUmqscUBub-Irvy4HduA",
      country: "KR",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "이탁수",
        "이탁수 news",
        "이탁수 South Korea"
      ],
      summary: "'전희철 딸' 전수완, 미스코리아 본선 가더니…배우 뺨치는 비주얼",
      detail: "'전희철 딸' 전수완, 미스코리아 본선 가더니…배우 뺨치는 비주얼\n이탁수 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "테라파워",
      slug: "kr-테라파워-2026-06-04",
      traffic: "200+",
      description: "“겨우 석달, 터만 닦았겠지 했더니”…사막 복판 우뚝 솟은 원전의 정체",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260605074500529",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTuhq6LbYWSEm13D8_UqEGomNG3JenRcrHP47_f4v951z86vjfml5U57_A7B5I",
      country: "KR",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "테라파워",
        "테라파워 news",
        "테라파워 South Korea"
      ],
      summary: "“겨우 석달, 터만 닦았겠지 했더니”…사막 복판 우뚝 솟은 원전의 정체",
      detail: "“겨우 석달, 터만 닦았겠지 했더니”…사막 복판 우뚝 솟은 원전의 정체\n테라파워 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IT: [
    {
      title: "silvia bonolis",
      slug: "it-silvia-bonolis-2026-06-04",
      traffic: "500+",
      description: "Sonia Bruganelli: “Mia figlia Silvia Bonolis è stata due mesi in ospedale per un importante intervento”",
      source: "Mediaset Infinity",
      sourceUrl: "https://mediasetinfinity.mediaset.it/news/mediasetinfinity/verissimo/sonia-bruganelli-ricovero-ospedale-figlia-silvia-importante-intervento_SE000000000023_t320iLha0RSUZeL56MomD85",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRs40Cf0bKRquNVzYOTuKsP0JvqwKMHVbnx8dDp71ZgAERUnrQTJyfXXTAjLJY",
      country: "IT",
      date: "2026-06-04",
      pubTime: "46m ago",
      relatedQueries: [
        "silvia bonolis",
        "silvia bonolis news",
        "silvia bonolis Italy"
      ],
      summary: "Sonia Bruganelli: “Mia figlia Silvia Bonolis è stata due mesi in ospedale per un importante intervento”",
      detail: "Sonia Bruganelli: “Mia figlia Silvia Bonolis è stata due mesi in ospedale per un importante intervento”\nsilvia bonolis is seeing increased search interest in Italy.\nSource: Mediaset Infinity.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "il verdetto",
      slug: "it-il-verdetto-2026-06-04",
      traffic: "500+",
      description: "The Michael Jackson Story, oggi gli ultimi due episodi della docuserie",
      source: "Sky TG24",
      sourceUrl: "https://tg24.sky.it/spettacolo/serie-tv/2026/06/03/michael-jackson-story-serie-sky",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcREUPc47ahnnkrVxdSUBKnwC7hre1JmY4hYpHj4QddlxDrPcHVB_TPD-EGfUys",
      country: "IT",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "il verdetto",
        "il verdetto news",
        "il verdetto Italy"
      ],
      summary: "The Michael Jackson Story, oggi gli ultimi due episodi della docuserie",
      detail: "The Michael Jackson Story, oggi gli ultimi due episodi della docuserie\nil verdetto is seeing increased search interest in Italy.\nSource: Sky TG24.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "protezione civile",
      slug: "it-protezione-civile-2026-06-04",
      traffic: "1000+",
      description: "Protezione Civile, in Veneto scatta il nuovo piano di allertamento: 25 zone a rischio e meteo mirato",
      source: "Montorioveronese.it",
      sourceUrl: "https://www.montorioveronese.it/2026/06/04/protezione-civile-in-veneto-scatta-il-nuovo-piano-di-allertamento-25-zone-a-rischio-e-meteo-mirato/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTLYFKlqPXJLoI96vEuCSQZ3wd5Fk6YgS7cB0c-RlYPhgC91KeAFREkGueuNTU",
      country: "IT",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "protezione civile",
        "protezione civile news",
        "protezione civile Italy"
      ],
      summary: "Protezione Civile, in Veneto scatta il nuovo piano di allertamento: 25 zone a rischio e meteo mirato",
      detail: "Protezione Civile, in Veneto scatta il nuovo piano di allertamento: 25 zone a rischio e meteo mirato\nprotezione civile is seeing increased search interest in Italy.\nSource: Montorioveronese.it.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "marco poggi",
      slug: "it-marco-poggi-2026-06-04",
      traffic: "5000+",
      description: "Marco Poggi in tv: «Hanno rovinato l'immagine di Chiara». Il fratello della ragazza uccisa a Garlasco rompe il silenzio dopo 19 anni",
      source: "Corriere Milano",
      sourceUrl: "https://milano.corriere.it/notizie/cronaca/26_giugno_04/marco-poggi-in-tv-hanno-rovinato-l-immagine-di-chiara-il-fratello-della-ragazza-uccisa-a-garlasco-rompe-il-silenzio-dopo-19-anni-7000ac1f-5ff5-438c-a25b-d3babe21axlk.shtml",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSmTF_Q3L381Rhm6dAdwnsLHNyF9B3rHCPncxZXhGmuLzQhkie5dcv1-6AF64k",
      country: "IT",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "marco poggi",
        "marco poggi news",
        "marco poggi Italy"
      ],
      summary: "Marco Poggi in tv: «Hanno rovinato l'immagine di Chiara». Il fratello della ragazza uccisa a Garlasco rompe il silenzio dopo 19 anni",
      detail: "Marco Poggi in tv: «Hanno rovinato l'immagine di Chiara». Il fratello della ragazza uccisa a Garlasco rompe il silenzio dopo 19 anni\nmarco poggi is seeing increased search interest in Italy.\nSource: Corriere Milano.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "costantino vitagliano",
      slug: "it-costantino-vitagliano-2026-06-04",
      traffic: "2000+",
      description: "\"Mettevo due maglioni sotto le giacche per riempire i vestiti, ho perso 38 chili. Prima di entrare in studio mi sono portato la mia siringa di cellule staminali\": Costantino Vitagliano torna a parlare della malattia",
      source: "Il Fatto Quotidiano",
      sourceUrl: "https://www.ilfattoquotidiano.it/2026/06/04/mettevo-due-maglioni-sotto-le-giacche-per-riempire-i-vestiti-ho-perso-38-chili-prima-di-entrare-in-studio-mi-sono-portato-la-mia-siringa-di-cellule-staminali-costantino-vitagliano-torna-a-parla/8408723/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRhZGfHpX0FlfpDXVirG8_AGbLkL9pg7XldbFWwxzm6FhLc9UfAPvzN3IC8IG8",
      country: "IT",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "costantino vitagliano",
        "costantino vitagliano news",
        "costantino vitagliano Italy"
      ],
      summary: "\"Mettevo due maglioni sotto le giacche per riempire i vestiti, ho perso 38 chili. Prima di entrare in studio mi sono portato la mia siringa di cellule staminali\": Costantino Vitagliano torna a parlare della malattia",
      detail: "\"Mettevo due maglioni sotto le giacche per riempire i vestiti, ho perso 38 chili. Prima di entrare in studio mi sono portato la mia siringa di cellule staminali\": Costantino Vitagliano torna a parlare della malattia\ncostantino vitagliano is seeing increased search interest in Italy.\nSource: Il Fatto Quotidiano.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  BR: [
    {
      title: "resumo de coração acelerado",
      slug: "br-resumo-de-corao-acelerado-2026-06-04",
      traffic: "2000+",
      description: "Em Coração Acelerado, Walmir confessa roubo e choca João Raul",
      source: "Gshow",
      sourceUrl: "https://gshow.globo.com/novelas/coracao-acelerado/vem-por-ai/noticia/em-coracao-acelerado-walmir-confessa-roubo-e-choca-joao-raul.ghtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRCiTTNoKW8HpGd7HGOQwRtVbpQ52rArkBr5-S8Iv28OBDnZXeL5JL2OBQfgBk",
      country: "BR",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "resumo de coração acelerado",
        "resumo de coração acelerado news",
        "resumo de coração acelerado Brazil"
      ],
      summary: "Em Coração Acelerado, Walmir confessa roubo e choca João Raul",
      detail: "Em Coração Acelerado, Walmir confessa roubo e choca João Raul\nresumo de coração acelerado is seeing increased search interest in Brazil.\nSource: Gshow.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "leonardo",
      slug: "br-leonardo-2026-06-04",
      traffic: "1000+",
      description: "Leonardo fica em saia justa com pergunta sobre Zé Felipe e Virginia: 'Vou tomar uma'; veja resposta",
      source: "Globo",
      sourceUrl: "https://revistaquem.globo.com/entretenimento/musica/sertanejo/noticia/2026/06/leonardo-fala-pela-primeira-vez-sobre-torcida-por-reconciliacao-de-virginia-e-ze-felipe.ghtml",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR-9Xymtz748xbYxkswjcu8oPfPb1qODpjnhkrmJlITbm4PyoxNiEZt2NVKBb0",
      country: "BR",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "leonardo",
        "leonardo news",
        "leonardo Brazil"
      ],
      summary: "Leonardo fica em saia justa com pergunta sobre Zé Felipe e Virginia: 'Vou tomar uma'; veja resposta",
      detail: "Leonardo fica em saia justa com pergunta sobre Zé Felipe e Virginia: 'Vou tomar uma'; veja resposta\nleonardo is seeing increased search interest in Brazil.\nSource: Globo.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "republica dominicana",
      slug: "br-republica-dominicana-2026-06-04",
      traffic: "1000+",
      description: "Ao vivo: Brasil x República Dominicana | Rodada 2 | Liga das Nações Feminina de Vôlei",
      source: "ge",
      sourceUrl: "https://ge.globo.com/volei/jogo/04-06-2026/brasil-republica-dominicana.ghtml",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLcuX0yr1ACd8nz3fSW00NyFX21AcOnj3NCVWY9ikCXbE6rMqFfjzrxpFXZc4",
      country: "BR",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "republica dominicana",
        "republica dominicana news",
        "republica dominicana Brazil"
      ],
      summary: "Ao vivo: Brasil x República Dominicana | Rodada 2 | Liga das Nações Feminina de Vôlei",
      detail: "Ao vivo: Brasil x República Dominicana | Rodada 2 | Liga das Nações Feminina de Vôlei\nrepublica dominicana is seeing increased search interest in Brazil.\nSource: ge.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "copa verde",
      slug: "br-copa-verde-2026-06-04",
      traffic: "1000+",
      description: "Anápolis x Paysandu: onde assistir ao vivo, horário e escalações",
      source: "ge",
      sourceUrl: "https://ge.globo.com/go/futebol/copa-verde/noticia/2026/06/04/anapolis-x-paysandu-onde-assistir-ao-vivo-horario-e-escalacoes.ghtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQTKr7YkF1PQkcgoemHy6AFqjNLe9_DKJg6G3lQDJKfxaOzB8Oa5lbtVLQik8s",
      country: "BR",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "copa verde",
        "copa verde news",
        "copa verde Brazil"
      ],
      summary: "Anápolis x Paysandu: onde assistir ao vivo, horário e escalações",
      detail: "Anápolis x Paysandu: onde assistir ao vivo, horário e escalações\ncopa verde is seeing increased search interest in Brazil.\nSource: ge.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "veja",
      slug: "br-veja-2026-06-04",
      traffic: "2000+",
      description: "Explosão em Copacabana revela local de refino de drogas; veja vídeo",
      source: "CNN Brasil",
      sourceUrl: "https://www.cnnbrasil.com.br/nacional/sudeste/rj/explosao-em-copacabana-revela-local-de-refino-de-drogas-veja-video/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQeVWmxLl7ItjsShwwjlE_PeseNIJgwGL2iqZVm0V23GWV6xXaAdQMd4-r1UII",
      country: "BR",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "veja",
        "veja news",
        "veja Brazil"
      ],
      summary: "Explosão em Copacabana revela local de refino de drogas; veja vídeo",
      detail: "Explosão em Copacabana revela local de refino de drogas; veja vídeo\nveja is seeing increased search interest in Brazil.\nSource: CNN Brasil.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IN: [
    {
      title: "भारती एयरटेल",
      slug: "in---2026-06-04",
      traffic: "100+",
      description: "Airtel के इस प्लान पर क्यों मचा है बवाल! आपका इंटरनेट भी हुआ स्लो?",
      source: "AajTak",
      sourceUrl: "https://www.aajtak.in/visualstories/technology/airtel-vip-internet-plan-net-neutrality-controversy-ttecm-281307-03-06-2026",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAd4WXPPl0wOC6frjpBHxLANjE-1pNqaJ50YszpPGkauXEvW6VE96emcMMk9k",
      country: "IN",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "भारती एयरटेल",
        "भारती एयरटेल news",
        "भारती एयरटेल India"
      ],
      summary: "Airtel के इस प्लान पर क्यों मचा है बवाल! आपका इंटरनेट भी हुआ स्लो?",
      detail: "Airtel के इस प्लान पर क्यों मचा है बवाल! आपका इंटरनेट भी हुआ स्लो?\nभारती एयरटेल is seeing increased search interest in India.\nSource: AajTak.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "peddi collection",
      slug: "in-peddi-collection-2026-06-04",
      traffic: "5000+",
      description: "‘Peddi’ movie review: Ram Charan and AR Rahman power a weakly-written sports drama",
      source: "The Hindu",
      sourceUrl: "https://www.thehindu.com/entertainment/movies/peddi-telugu-movie-review-ram-charan-and-ar-rahman-power-a-weakly-written-sports-drama/article71060308.ece",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQQg4xzd655ZV8S0VUxAesNzou3M7QjgUbAD_EzTOsemgSQ_Ddpti5tDIgrtv8",
      country: "IN",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "peddi collection",
        "peddi collection news",
        "peddi collection India"
      ],
      summary: "‘Peddi’ movie review: Ram Charan and AR Rahman power a weakly-written sports drama",
      detail: "‘Peddi’ movie review: Ram Charan and AR Rahman power a weakly-written sports drama\npeddi collection is seeing increased search interest in India.\nSource: The Hindu.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "துரை வைகோ",
      slug: "in---2026-06-04",
      traffic: "100+",
      description: "வேறு கட்சியின் சின்னத்தில் போட்டியிடக்கூடாது: துரை வைகோ கருத்து",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/tamil/articles/c3v2vxdq702o",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSD9kWQMi1m0N3NgMIOWwt3WO_dv9dI7Qgt9oH7FDCI8fp8PqxjUT_uC4jgI7c",
      country: "IN",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "துரை வைகோ",
        "துரை வைகோ news",
        "துரை வைகோ India"
      ],
      summary: "வேறு கட்சியின் சின்னத்தில் போட்டியிடக்கூடாது: துரை வைகோ கருத்து",
      detail: "வேறு கட்சியின் சின்னத்தில் போட்டியிடக்கூடாது: துரை வைகோ கருத்து\nதுரை வைகோ is seeing increased search interest in India.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "रेनुका इसरानी",
      slug: "in---2026-06-04",
      traffic: "100+",
      description: "59 की उम्र में कुंवारी है महाभारत की गांधारी, परिवार के लिए त्यागा करियर, नहीं रचाई शादी",
      source: "AajTak",
      sourceUrl: "https://www.aajtak.in/entertainment/television/photo/mahabharat-gandhari-renuka-israni-unmarried-at-age-of-59-quit-acting-for-old-parents-tmovb-2570184-2026-06-04",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRgbzS805RfBN8KWUymsQiA9M_PVBYkuWBYdU0UmzehbZv3-pdN6F2wRDcCfuY",
      country: "IN",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "रेनुका इसरानी",
        "रेनुका इसरानी news",
        "रेनुका इसरानी India"
      ],
      summary: "59 की उम्र में कुंवारी है महाभारत की गांधारी, परिवार के लिए त्यागा करियर, नहीं रचाई शादी",
      detail: "59 की उम्र में कुंवारी है महाभारत की गांधारी, परिवार के लिए त्यागा करियर, नहीं रचाई शादी\nरेनुका इसरानी is seeing increased search interest in India.\nSource: AajTak.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  ES: [
    {
      title: "expulsado supervivientes",
      slug: "es-expulsado-supervivientes-2026-06-04",
      traffic: "200+",
      description: "'Supervivientes 2026': Tierra de nadie 13 (02/06/26), completo",
      source: "Telecinco",
      sourceUrl: "https://www.telecinco.es/television/a-la-carta/20260603/supervivientes-tierra-nadie-13-completo_18_019337995.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR1HWtaQrSnDmD-DqdFosaSW4xfHoOWzNzZhLrs4Q9t4U7glOyKSm-sGFnch70",
      country: "ES",
      date: "2026-06-04",
      pubTime: "16m ago",
      relatedQueries: [
        "expulsado supervivientes",
        "expulsado supervivientes news",
        "expulsado supervivientes Spain"
      ],
      summary: "'Supervivientes 2026': Tierra de nadie 13 (02/06/26), completo",
      detail: "'Supervivientes 2026': Tierra de nadie 13 (02/06/26), completo\nexpulsado supervivientes is seeing increased search interest in Spain.\nSource: Telecinco.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "kvaratskhelia",
      slug: "es-kvaratskhelia-2026-06-04",
      traffic: "500+",
      description: "Valores de mercado Ligue 1: Kvaratskhelia protagoniza la mayor subida; Fabián, devaluado",
      source: "Transfermarkt",
      sourceUrl: "https://www.transfermarkt.es/valores-de-mercado-ligue-1-kvaratskhelia-protagoniza-la-mayor-subida-fabian-devaluado/view/news/480340",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTfuXK1NdCSCZwdijiIs0qeWvbYhlDX_ARcnVxLN7HL4hZO4QVUyw4b31QD0Lk",
      country: "ES",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "kvaratskhelia",
        "kvaratskhelia news",
        "kvaratskhelia Spain"
      ],
      summary: "Valores de mercado Ligue 1: Kvaratskhelia protagoniza la mayor subida; Fabián, devaluado",
      detail: "Valores de mercado Ligue 1: Kvaratskhelia protagoniza la mayor subida; Fabián, devaluado\nkvaratskhelia is seeing increased search interest in Spain.\nSource: Transfermarkt.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "dembele",
      slug: "es-dembele-2026-06-04",
      traffic: "500+",
      description: "Francia mima (ahora sí) a Dembélé",
      source: "SPORT",
      sourceUrl: "https://www.sport.es/es/noticias/mundial-futbol/francia-mima-ahora-dembele-130960360",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpvpT--flMc6GvhPQEU0VmZO7xmF_VkV1u8J__ooUuFJw-HEAXASXywM1OsOk",
      country: "ES",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "dembele",
        "dembele news",
        "dembele Spain"
      ],
      summary: "Francia mima (ahora sí) a Dembélé",
      detail: "Francia mima (ahora sí) a Dembélé\ndembele is seeing increased search interest in Spain.\nSource: SPORT.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "doue",
      slug: "es-doue-2026-06-04",
      traffic: "2000+",
      description: "France vs Ivory Coast: Friendlies stats & head-to-head",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/live/cwy2zry55j0t",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRRwOvZeQ1RCOectFBbNzb90RO0iFo7744EKusCTrxY7EliGaxoFxKykWOMiEA",
      country: "ES",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "doue",
        "doue news",
        "doue Spain"
      ],
      summary: "France vs Ivory Coast: Friendlies stats & head-to-head",
      detail: "France vs Ivory Coast: Friendlies stats & head-to-head\ndoue is seeing increased search interest in Spain.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  CH: [
    {
      title: "frankreich elfenbeinküste",
      slug: "ch-frankreich-elfenbeinkste-2026-06-04",
      traffic: "2000+",
      description: "Testspiele vor WM 2026 - Elfenbeinküste schockt Frankreich spät – Irak überrascht Spanien",
      source: "SRF",
      sourceUrl: "https://www.srf.ch/sport/fussball/fifa-wm-2026/testspiele-vor-wm-2026-elfenbeinkueste-schockt-frankreich-spaet-irak-ueberrascht-spanien",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSr8a1t2hF2v9r6yAxwXpQ4rB7ZXyDS9QEb7MwxWwUtgsq2B1k8F0QSxJpYIv0",
      country: "CH",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "frankreich elfenbeinküste",
        "frankreich elfenbeinküste news",
        "frankreich elfenbeinküste Switzerland"
      ],
      summary: "Testspiele vor WM 2026 - Elfenbeinküste schockt Frankreich spät – Irak überrascht Spanien",
      detail: "Testspiele vor WM 2026 - Elfenbeinküste schockt Frankreich spät – Irak überrascht Spanien\nfrankreich elfenbeinküste is seeing increased search interest in Switzerland.\nSource: SRF.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "sankt gallen",
      slug: "ch-sankt-gallen-2026-06-04",
      traffic: "200+",
      description: "FCSG Cupsieg – wir gratulieren!",
      source: "stadt.sg.ch",
      sourceUrl: "https://www.stadt.sg.ch/news/stsg_entsorgung/2026/05/cupsieg.html",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRiaiV3g5LKvEmrhrxBt-GdVv9l_XeR3414lpXhw2nyMpZYAEUtk0VAc2C6ef8",
      country: "CH",
      date: "2026-06-04",
      pubTime: "3h ago",
      relatedQueries: [
        "sankt gallen",
        "sankt gallen news",
        "sankt gallen Switzerland"
      ],
      summary: "FCSG Cupsieg – wir gratulieren!",
      detail: "FCSG Cupsieg – wir gratulieren!\nsankt gallen is seeing increased search interest in Switzerland.\nSource: stadt.sg.ch.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "schweiz heute",
      slug: "ch-schweiz-heute-2026-06-04",
      traffic: "500+",
      description: "CH Media lanciert neues Newsportal «Schweiz heute»",
      source: "Watson",
      sourceUrl: "https://www.watson.ch/schweiz/medien/556428408-ch-media-lanciert-neues-newsportal-schweiz-heute",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTLr0DpUi6K3OI2do38_Gj2tIktGc3uLPDBx9eSdai9twy3Ht1jD-vkbtMal-g",
      country: "CH",
      date: "2026-06-04",
      pubTime: "3h ago",
      relatedQueries: [
        "schweiz heute",
        "schweiz heute news",
        "schweiz heute Switzerland"
      ],
      summary: "CH Media lanciert neues Newsportal «Schweiz heute»",
      detail: "CH Media lanciert neues Newsportal «Schweiz heute»\nschweiz heute is seeing increased search interest in Switzerland.\nSource: Watson.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "migros-restaurant",
      slug: "ch-migros-restaurant-2026-06-04",
      traffic: "500+",
      description: "Restaurantschliessungen der Migros sorgen für Unmut",
      source: "Blick",
      sourceUrl: "https://www.blick.ch/community/restaurantschliessungen-sorgen-fuer-unmut-die-migros-spart-sich-in-eine-wachsende-kundenunfreundlichkeit-id22003114.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUwcLHPhzGLBS2VRc3JuL-5Hg7cojVN8yNuMutFjRwYT8tF9g2etcYapfciug",
      country: "CH",
      date: "2026-06-04",
      pubTime: "3h ago",
      relatedQueries: [
        "migros-restaurant",
        "migros-restaurant news",
        "migros-restaurant Switzerland"
      ],
      summary: "Restaurantschliessungen der Migros sorgen für Unmut",
      detail: "Restaurantschliessungen der Migros sorgen für Unmut\nmigros-restaurant is seeing increased search interest in Switzerland.\nSource: Blick.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "spain vs iraq",
      slug: "ch-spain-vs-iraq-2026-06-04",
      traffic: "200+",
      description: "Spain vs Iraq: Friendlies stats & head-to-head",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/live/c9q3rx8qqp4t",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRRwOvZeQ1RCOectFBbNzb90RO0iFo7744EKusCTrxY7EliGaxoFxKykWOMiEA",
      country: "CH",
      date: "2026-06-04",
      pubTime: "4h ago",
      relatedQueries: [
        "spain vs iraq",
        "spain vs iraq news",
        "spain vs iraq Switzerland"
      ],
      summary: "Spain vs Iraq: Friendlies stats & head-to-head",
      detail: "Spain vs Iraq: Friendlies stats & head-to-head\nspain vs iraq is seeing increased search interest in Switzerland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  MX: [
    {
      title: "chequia - guatemala",
      slug: "mx-chequia-guatemala-2026-06-04",
      traffic: "1000+",
      description: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara",
      source: "ESPN México",
      sourceUrl: "https://www.espn.com.mx/futbol/guatemala/nota/_/id/16795807/ausencia-rubio-rubin-nathaniel-mendez-laing-seleccion-guatemala-luis-fernando-tena",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ45nQR4jTRQhcStbFFa91a61m6WohzpO727-ROHiJByd1EFrzn7g9ExsyZ6ZA",
      country: "MX",
      date: "2026-06-04",
      pubTime: "6m ago",
      relatedQueries: [
        "chequia - guatemala",
        "chequia - guatemala news",
        "chequia - guatemala Mexico"
      ],
      summary: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara",
      detail: "¿Por qué están ausentes Rubio Rubín y Nathaniel Méndez-Laing? Luis Fernando Tena lo aclara\nchequia - guatemala is seeing increased search interest in Mexico.\nSource: ESPN México.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "a que hora juega mexico",
      slug: "mx-a-que-hora-juega-mexico-2026-06-04",
      traffic: "2000+",
      description: "México vs Serbia: posibles alineaciones para el partido amistoso",
      source: "ESPN México",
      sourceUrl: "https://www.espn.com.mx/futbol/mundial/nota/_/id/16794561/mexico-vs-serbia-alineaciones-que-debes-saber-partido-amistoso-2026",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTGet-MmWYz2BisZptEvYaGdlCb8hRerIbLYvS-Oi0aDqY9h096O_9h8JA1WMg",
      country: "MX",
      date: "2026-06-04",
      pubTime: "26m ago",
      relatedQueries: [
        "a que hora juega mexico",
        "a que hora juega mexico news",
        "a que hora juega mexico Mexico"
      ],
      summary: "México vs Serbia: posibles alineaciones para el partido amistoso",
      detail: "México vs Serbia: posibles alineaciones para el partido amistoso\na que hora juega mexico is seeing increased search interest in Mexico.\nSource: ESPN México.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "5 de junio",
      slug: "mx-5-de-junio-2026-06-04",
      traffic: "2000+",
      description: "¿Regresa el Doble No Circula 4 de Junio por Contingencia? CAMe Da Restricción en CDMX-Edomex",
      source: "N+",
      sourceUrl: "https://www.nmas.com.mx/ciudad-de-mexico/movilidad/regresa-doble-hoy-no-circula-4-de-junio-2026-contingencia-came-restriccion-cdmx-edomex/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRlU5CDhG0w6SyEY-sSrgtUY2cmcjVg9Rz6GhQREO3BpUWNjoj6Nt9NAQL0xUs",
      country: "MX",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "5 de junio",
        "5 de junio news",
        "5 de junio Mexico"
      ],
      summary: "¿Regresa el Doble No Circula 4 de Junio por Contingencia? CAMe Da Restricción en CDMX-Edomex",
      detail: "¿Regresa el Doble No Circula 4 de Junio por Contingencia? CAMe Da Restricción en CDMX-Edomex\n5 de junio is seeing increased search interest in Mexico.\nSource: N+.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "tepeaca noticias",
      slug: "mx-tepeaca-noticias-2026-06-04",
      traffic: "2000+",
      description: "Estallan cuatro pipas de presunto 'huachicol' de gas en Tepeaca, Puebla; evacuan a 2 mil personas",
      source: "La Jornada",
      sourceUrl: "https://www.jornada.com.mx/noticia/2026/06/04/estados/estallan-tres-pipas-de-presunto-huachicol-de-gas-en-tepeaca-puebla-evacuan-escuela-cercana",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz-VdsaHizb_RVKcW_J4OVQhX7-emr1mUKCyKT5KOnH1fUaXzvsBqEwkEIg6w",
      country: "MX",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "tepeaca noticias",
        "tepeaca noticias news",
        "tepeaca noticias Mexico"
      ],
      summary: "Estallan cuatro pipas de presunto 'huachicol' de gas en Tepeaca, Puebla; evacuan a 2 mil personas",
      detail: "Estallan cuatro pipas de presunto 'huachicol' de gas en Tepeaca, Puebla; evacuan a 2 mil personas\ntepeaca noticias is seeing increased search interest in Mexico.\nSource: La Jornada.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "sherpa",
      slug: "mx-sherpa-2026-06-04",
      traffic: "200+",
      description: "Mount Everest: Sherpa guide found alive after going missing for six days",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/cvgz2yjl4y3o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQZUqa5vG_ne1pkAHS92GUC99ECwikC0IalmcHlaOAtfqnKJCTvL8waizDHCLM",
      country: "MX",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "sherpa",
        "sherpa news",
        "sherpa Mexico"
      ],
      summary: "Mount Everest: Sherpa guide found alive after going missing for six days",
      detail: "Mount Everest: Sherpa guide found alive after going missing for six days\nsherpa is seeing increased search interest in Mexico.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  PL: [
    {
      title: "majka jeżowska",
      slug: "pl-majka-jeowska-2026-06-04",
      traffic: "2000+",
      description: "\"Niedopuszczalne, pod publiczkę\". Minister reaguje na słowa Skolima",
      source: "PolsatNews.pl",
      sourceUrl: "https://www.polsatnews.pl/wiadomosc/2026-06-02/jestem-wzburzona-minister-kultury-o-dyskusji-ws-emerytur-dla-artystow/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXxPC3e2UB9BVW_hl530RP6NmJCq3AxTcgnN4f6vFgdF00H4orPcQ0NQW5Uec",
      country: "PL",
      date: "2026-06-04",
      pubTime: "56m ago",
      relatedQueries: [
        "majka jeżowska",
        "majka jeżowska news",
        "majka jeżowska Poland"
      ],
      summary: "\"Niedopuszczalne, pod publiczkę\". Minister reaguje na słowa Skolima",
      detail: "\"Niedopuszczalne, pod publiczkę\". Minister reaguje na słowa Skolima\nmajka jeżowska is seeing increased search interest in Poland.\nSource: PolsatNews.pl.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "orłoś",
      slug: "pl-oro-2026-06-04",
      traffic: "500+",
      description: "Program tv dla Daję słowo - Maciej Orłoś",
      source: "Pilot WP",
      sourceUrl: "https://pilot.wp.pl/program-tv/program/daje-slowo-maciej-orlos-e38842ab57684f9edb982006e064ceab",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2WoOthzzz-om-ni1I7lIlkAMC6hb68UYHpved4yQGm1clIJMcD_g3J-kyj-c",
      country: "PL",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "orłoś",
        "orłoś news",
        "orłoś Poland"
      ],
      summary: "Program tv dla Daję słowo - Maciej Orłoś",
      detail: "Program tv dla Daję słowo - Maciej Orłoś\norłoś is seeing increased search interest in Poland.\nSource: Pilot WP.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "natalia kukulska",
      slug: "pl-natalia-kukulska-2026-06-04",
      traffic: "2000+",
      description: "Festiwal w Opolu. Symboliczna decyzja Kukulskiej. \"To będzie dla mnie koniec\"",
      source: "Do Rzeczy",
      sourceUrl: "https://dorzeczy.pl/kraj/896644/festiwal-w-opolu-symboliczna-decyzja-kukulskiej-to-bedzie-dla-mnie-koniec.html",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8i2gTqDBZ2RrBBGsv9IJJSwbDtmD7u8cEVnTU9AAhoT-dv2GGDIYwYirEb4U",
      country: "PL",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "natalia kukulska",
        "natalia kukulska news",
        "natalia kukulska Poland"
      ],
      summary: "Festiwal w Opolu. Symboliczna decyzja Kukulskiej. \"To będzie dla mnie koniec\"",
      detail: "Festiwal w Opolu. Symboliczna decyzja Kukulskiej. \"To będzie dla mnie koniec\"\nnatalia kukulska is seeing increased search interest in Poland.\nSource: Do Rzeczy.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "dawid kwiatkowski",
      slug: "pl-dawid-kwiatkowski-2026-06-04",
      traffic: "2000+",
      description: "Dawid Kwiatkowski po siedmiu latach wraca do Opola. \"Kurczę, tęskniłem\"",
      source: "Onet",
      sourceUrl: "https://www.onet.pl/styl-zycia/plejada/dawid-kwiatkowski-po-7-latach-wraca-do-opola-tak-wypadl-na-probie-generalnej/7973qv4,0898b825",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx27zhJzpGQzwSs7mRPA-eCCPhZEyE2c5uFyJrvMCIgnejHQUOfjNMDJ7qUQA",
      country: "PL",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "dawid kwiatkowski",
        "dawid kwiatkowski news",
        "dawid kwiatkowski Poland"
      ],
      summary: "Dawid Kwiatkowski po siedmiu latach wraca do Opola. \"Kurczę, tęskniłem\"",
      detail: "Dawid Kwiatkowski po siedmiu latach wraca do Opola. \"Kurczę, tęskniłem\"\ndawid kwiatkowski is seeing increased search interest in Poland.\nSource: Onet.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "grzegorz skawiński",
      slug: "pl-grzegorz-skawiski-2026-06-04",
      traffic: "5000+",
      description: "Skawiński w Opolu zwrócił się do Chylińskiej. \"Zostawię to sobie na koniec...\"",
      source: "Onet",
      sourceUrl: "https://www.onet.pl/styl-zycia/plejada/skawinski-w-opolu-zwrocil-sie-do-chylinskiej-zostawie-to-sobie-na-koniec/xewt2zg,0898b825",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQttHLWTHrJJuXLofPlYAoMNfRXH4XHr0GxjyWmhWva3vvsDsE5-c3iSZfunjY",
      country: "PL",
      date: "2026-06-04",
      pubTime: "2h ago",
      relatedQueries: [
        "grzegorz skawiński",
        "grzegorz skawiński news",
        "grzegorz skawiński Poland"
      ],
      summary: "Skawiński w Opolu zwrócił się do Chylińskiej. \"Zostawię to sobie na koniec...\"",
      detail: "Skawiński w Opolu zwrócił się do Chylińskiej. \"Zostawię to sobie na koniec...\"\ngrzegorz skawiński is seeing increased search interest in Poland.\nSource: Onet.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  HK: [
    {
      title: "杨佩洁",
      slug: "hk-杨佩洁-2026-06-04",
      traffic: "100+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "HK",
      date: "2026-06-04",
      pubTime: "1h ago",
      relatedQueries: [
        "杨佩洁",
        "杨佩洁 news",
        "杨佩洁 Hong Kong"
      ],
      summary: "杨佩洁 is trending in Hong Kong.",
      detail: "杨佩洁 is trending in Hong Kong.\n杨佩洁 is seeing increased search interest in Hong Kong.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "私煙",
      slug: "hk-私煙-2026-06-04",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "HK",
      date: "2026-06-04",
      pubTime: "8h ago",
      relatedQueries: [
        "私煙",
        "私煙 news",
        "私煙 Hong Kong"
      ],
      summary: "私煙 is trending in Hong Kong.",
      detail: "私煙 is trending in Hong Kong.\n私煙 is seeing increased search interest in Hong Kong.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ]
};

export function getPreloadedTrends(countryCode: string): TrendItem[] {
  return preloadedTrends[countryCode] || [];
}
