// Auto-generated by update-trends.mjs
// Last updated: 2026-05-28T20:57:27.047Z
// DO NOT EDIT MANUALLY - this file is overwritten every 30 minutes

import { TrendItem } from "@/lib/google-trends";

const today = new Date().toISOString().split("T")[0];

export const preloadedTrends: Record<string, TrendItem[]> = {
  US: [
    {
      title: "arthur rinderknech",
      slug: "us-arthur-rinderknech-2026-05-28",
      traffic: "500+",
      description: "French Open Men’s Day 5 Predictions Including Arthur Rinderknech vs Matteo Berrettini",
      source: "Last Word On Sports",
      sourceUrl: "https://lastwordonsports.com/tennis/2026/05/27/french-open-mens-day-5-predictions-rinderknech-berrettini/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQQ8zktIyWq2Tr_uVPC-iGlmI8zhNO3QSvV-WAjE8J4-rNQPiOfF6eoncZFdjY",
      country: "US",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "arthur rinderknech",
        "arthur rinderknech news",
        "arthur rinderknech United States"
      ],
      summary: "French Open Men’s Day 5 Predictions Including Arthur Rinderknech vs Matteo Berrettini",
      detail: "French Open Men’s Day 5 Predictions Including Arthur Rinderknech vs Matteo Berrettini\narthur rinderknech is seeing increased search interest in United States.\nSource: Last Word On Sports.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "chris sale",
      slug: "us-chris-sale-2026-05-28",
      traffic: "2000+",
      description: "Game 55: Braves at Red Sox lineups and notes",
      source: "The Boston Globe",
      sourceUrl: "https://www.bostonglobe.com/2026/05/28/sports/red-sox-braves-preview-may-28/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRdhuJWqkxXAxECu8At0GlaqnSWcXUwZuWWNMFYb_XoQ41ENDRxtbsNslIq7ws",
      country: "US",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "chris sale",
        "chris sale news",
        "chris sale United States"
      ],
      summary: "Game 55: Braves at Red Sox lineups and notes",
      detail: "Game 55: Braves at Red Sox lineups and notes\nchris sale is seeing increased search interest in United States.\nSource: The Boston Globe.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ronda rousey holly holm rematch",
      slug: "us-ronda-rousey-holly-holm-rematch-2026-05-28",
      traffic: "500+",
      description: "Ronda Rousey responds to Holly Holm’s rematch request, would ‘clean her clock’ and ‘re-write’ UFC history",
      source: "Yahoo Sports",
      sourceUrl: "https://sports.yahoo.com/articles/ronda-rousey-responds-holly-holm-155325638.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTzFC1tjaBnWTdBsU60rm9mQJOPyuukmbmHR5hq2gvogMf8x4dSzZ3rGERBWYs",
      country: "US",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "ronda rousey holly holm rematch",
        "ronda rousey holly holm rematch news",
        "ronda rousey holly holm rematch United States"
      ],
      summary: "Ronda Rousey responds to Holly Holm’s rematch request, would ‘clean her clock’ and ‘re-write’ UFC history",
      detail: "Ronda Rousey responds to Holly Holm’s rematch request, would ‘clean her clock’ and ‘re-write’ UFC history\nronda rousey holly holm rematch is seeing increased search interest in United States.\nSource: Yahoo Sports.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "paulina porizkova",
      slug: "us-paulina-porizkova-2026-05-28",
      traffic: "200+",
      description: "Paulina Porizkova says she's being evicted from her apartment just four days before her wedding in Italy",
      source: "Fox News",
      sourceUrl: "https://www.foxnews.com/entertainment/paulina-porizkova-says-shes-evicted-apartment-four-days-wedding-italy",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSlO-Ao-WhmAw9bny7W8yxOSEE4-HD1iwWFR-Zvm_gCnBOxBdj7mAH1ZUFKQqU",
      country: "US",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "paulina porizkova",
        "paulina porizkova news",
        "paulina porizkova United States"
      ],
      summary: "Paulina Porizkova says she's being evicted from her apartment just four days before her wedding in Italy",
      detail: "Paulina Porizkova says she's being evicted from her apartment just four days before her wedding in Italy\npaulina porizkova is seeing increased search interest in United States.\nSource: Fox News.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "costco stock",
      slug: "us-costco-stock-2026-05-28",
      traffic: "2000+",
      description: "Costco Nearing All-Time High: Buy, Sell or Hold?",
      source: "Yahoo Finance",
      sourceUrl: "https://finance.yahoo.com/markets/stocks/articles/costco-nearing-time-high-buy-133743096.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSz33RgzIWKvDuW5osLYEeqcWIv3jQTG_0n8lB2Tf895kEplMy1Xgk8NA3GciE",
      country: "US",
      date: "2026-05-28",
      pubTime: "47m ago",
      relatedQueries: [
        "costco stock",
        "costco stock news",
        "costco stock United States"
      ],
      summary: "Costco Nearing All-Time High: Buy, Sell or Hold?",
      detail: "Costco Nearing All-Time High: Buy, Sell or Hold?\ncostco stock is seeing increased search interest in United States.\nSource: Yahoo Finance.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  GB: [
    {
      title: "iran us",
      slug: "gb-iran-us-2026-05-28",
      traffic: "1000+",
      description: "US and Iran reach tentative deal to extend ceasefire, US officials say",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/news/articles/c87qng40wz9o",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSatFKtPEJruRCRhxhmMcpl9C_3gHe856ym_y95KD_iqGhNBhtLbIfCfcng82Y",
      country: "GB",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "iran us",
        "iran us news",
        "iran us United Kingdom"
      ],
      summary: "US and Iran reach tentative deal to extend ceasefire, US officials say",
      detail: "US and Iran reach tentative deal to extend ceasefire, US officials say\niran us is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jeremy sarmiento",
      slug: "gb-jeremy-sarmiento-2026-05-28",
      traffic: "100+",
      description: "'Spygate' victims confirm summer deal for Albion winger",
      source: "The Argus",
      sourceUrl: "https://www.theargus.co.uk/sport/26148057.jeremy-sarmientos-championship-loan-deal-made-permanent/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6SHKKVSaq7MubflKPczGd4eBv8cUmr1V8ImtWRND71S9kLPBvCIu6pZ0RDLo",
      country: "GB",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "jeremy sarmiento",
        "jeremy sarmiento news",
        "jeremy sarmiento United Kingdom"
      ],
      summary: "'Spygate' victims confirm summer deal for Albion winger",
      detail: "'Spygate' victims confirm summer deal for Albion winger\njeremy sarmiento is seeing increased search interest in United Kingdom.\nSource: The Argus.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "putin",
      slug: "gb-putin-2026-05-28",
      traffic: "500+",
      description: "Russia ramps up threats against Ukraine. What does that say about the war?",
      source: "BBC",
      sourceUrl: "https://www.bbc.co.uk/news/articles/c3v22ylzpqzo",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSr8Hr4dzNoGqAaYcTtMO0f7INbEQjz6biiaxCQokkt11km_R9WZ3ygsH72zbM",
      country: "GB",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "putin",
        "putin news",
        "putin United Kingdom"
      ],
      summary: "Russia ramps up threats against Ukraine. What does that say about the war?",
      detail: "Russia ramps up threats against Ukraine. What does that say about the war?\nputin is seeing increased search interest in United Kingdom.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "konate",
      slug: "gb-konate-2026-05-28",
      traffic: "500+",
      description: "Ibrahima Konaté’s Liverpool Contract: What Are the Latest Updates?",
      source: "Sports Illustrated",
      sourceUrl: "https://www.si.com/soccer/ibrahima-konate-liverpool-contract-latest-updates",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8SBk6rrVS3H2_QAxv55UoMe-ZIcOkBjtg_54sjD2G7HG6TX153gO5xH-gZVc",
      country: "GB",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "konate",
        "konate news",
        "konate United Kingdom"
      ],
      summary: "Ibrahima Konaté’s Liverpool Contract: What Are the Latest Updates?",
      detail: "Ibrahima Konaté’s Liverpool Contract: What Are the Latest Updates?\nkonate is seeing increased search interest in United Kingdom.\nSource: Sports Illustrated.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "vladimir putin",
      slug: "gb-vladimir-putin-2026-05-28",
      traffic: "200+",
      description: "Russia signs $16.5 billion deal to build first nuclear power plant in Kazakhstan",
      source: "Reuters",
      sourceUrl: "https://www.reuters.com/business/energy/russia-signs-agreement-build-nuclear-power-plant-kazakhstan-2026-05-28/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS6PHw2mWeayzzLG-sqq3-ORKlJiJb-83YfL2PgGlLpjelJZscL6X9mNCmRazU",
      country: "GB",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "vladimir putin",
        "vladimir putin news",
        "vladimir putin United Kingdom"
      ],
      summary: "Russia signs $16.5 billion deal to build first nuclear power plant in Kazakhstan",
      detail: "Russia signs $16.5 billion deal to build first nuclear power plant in Kazakhstan\nvladimir putin is seeing increased search interest in United Kingdom.\nSource: Reuters.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  DE: [
    {
      title: "dell aktie",
      slug: "de-dell-aktie-2026-05-28",
      traffic: "200+",
      description: "Dell angelt sich 10 Milliarden-Deal mit dem Pentagon",
      source: "Wallstreet Online",
      sourceUrl: "https://www.wallstreet-online.de/nachricht/20936358-aktie-stoppen-dell-angelt-10-milliarden-deal-pentagon",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTegrAUv7FZVUTMnitzJiBLCg2BRqvoZF2AJRmhCNki4wfUcpB38JpjHDALIzg",
      country: "DE",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "dell aktie",
        "dell aktie news",
        "dell aktie Germany"
      ],
      summary: "Dell angelt sich 10 Milliarden-Deal mit dem Pentagon",
      detail: "Dell angelt sich 10 Milliarden-Deal mit dem Pentagon\ndell aktie is seeing increased search interest in Germany.\nSource: Wallstreet Online.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "ricarda lang",
      slug: "de-ricarda-lang-2026-05-28",
      traffic: "2000+",
      description: "\"Einfach weiterscrollen\": Ricarda Lang verteidigt ihr Sportfoto gegen Hater",
      source: "Ntv",
      sourceUrl: "https://www.n-tv.de/leute/Ricarda-Lang-verteidigt-ihr-Sportfoto-gegen-Hater-id30857821.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTcvE7icnlEMcqUm960F9lReoo9jc4ZiMDWK_imKiA8cvXAfGkW7UaldTM4B3w",
      country: "DE",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "ricarda lang",
        "ricarda lang news",
        "ricarda lang Germany"
      ],
      summary: "\"Einfach weiterscrollen\": Ricarda Lang verteidigt ihr Sportfoto gegen Hater",
      detail: "\"Einfach weiterscrollen\": Ricarda Lang verteidigt ihr Sportfoto gegen Hater\nricarda lang is seeing increased search interest in Germany.\nSource: Ntv.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "thorsten frei",
      slug: "de-thorsten-frei-2026-05-28",
      traffic: "200+",
      description: "Pflegeversicherung: Warum Kinderlose mehr einzahlen",
      source: "BR",
      sourceUrl: "https://www.br.de/nachrichten/wirtschaft/pflegeversicherung-warum-kinderlose-mehr-einzahlen,VKtjK2F",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdjzCCLnDXaoj48pKqtj0lT9G1-Pdc2Z2UO6rc3WXarS9yuNQQAyYZ1Zo4XH4",
      country: "DE",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "thorsten frei",
        "thorsten frei news",
        "thorsten frei Germany"
      ],
      summary: "Pflegeversicherung: Warum Kinderlose mehr einzahlen",
      detail: "Pflegeversicherung: Warum Kinderlose mehr einzahlen\nthorsten frei is seeing increased search interest in Germany.\nSource: BR.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "nordhausen",
      slug: "de-nordhausen-2026-05-28",
      traffic: "200+",
      description: "25 Millionen Euro auf der Kippe: Unternehmen aus dem Kreis Nordhausen stellt plötzlich Standort infrage",
      source: "Thüringer Allgemeine",
      sourceUrl: "https://www.thueringer-allgemeine.de/lokales/nordhausen/article412109662/25-millionen-euro-auf-der-kippe-unternehmen-aus-dem-kreis-nordhausen-stellt-ploetzlich-standort-infrage.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSwZkDy5CQt-YcREbodlJIoDNwc4Ezn1CPhbm-EZEfDYGpaZ_nd_xbLNwdeivM",
      country: "DE",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "nordhausen",
        "nordhausen news",
        "nordhausen Germany"
      ],
      summary: "25 Millionen Euro auf der Kippe: Unternehmen aus dem Kreis Nordhausen stellt plötzlich Standort infrage",
      detail: "25 Millionen Euro auf der Kippe: Unternehmen aus dem Kreis Nordhausen stellt plötzlich Standort infrage\nnordhausen is seeing increased search interest in Germany.\nSource: Thüringer Allgemeine.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "maybrit illner",
      slug: "de-maybrit-illner-2026-05-28",
      traffic: "2000+",
      description: "\"Maybrit Illner\" heute: Die Gäste am 28. Mai 2026 im Überblick",
      source: "T-Online",
      sourceUrl: "https://www.t-online.de/unterhaltung/tv/talkshows/id_101269450/-maybrit-illner-heute-das-sind-die-gaeste-am-donnerstag-ein-ueberblick.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS_3JFLoszf1pp5clrdL4ckGJex9dElCKgxOoOLRInTi3qMCDTgro4ySn5ByQg",
      country: "DE",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "maybrit illner",
        "maybrit illner news",
        "maybrit illner Germany"
      ],
      summary: "\"Maybrit Illner\" heute: Die Gäste am 28. Mai 2026 im Überblick",
      detail: "\"Maybrit Illner\" heute: Die Gäste am 28. Mai 2026 im Überblick\nmaybrit illner is seeing increased search interest in Germany.\nSource: T-Online.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  JP: [
    {
      title: "中村敬斗",
      slug: "jp-中村敬斗-2026-05-28",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "JP",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "中村敬斗",
        "中村敬斗 news",
        "中村敬斗 Japan"
      ],
      summary: "中村敬斗 is trending in Japan.",
      detail: "中村敬斗 is trending in Japan.\n中村敬斗 is seeing increased search interest in Japan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "奈良新聞",
      slug: "jp-奈良新聞-2026-05-28",
      traffic: "100+",
      description: "息子装い女性から150万円詐取疑い 21歳「指示役」を逮捕（FNNプライムオンライン（フジテレビ系））",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/b8b0a230c3036d1a7d6feae8ac9a3484766c1580",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGADO_WLKztF-i0_HoF0PD7brlQV7R_BfO1vGEzDdX4azamAHKJBO_7gd1zHo",
      country: "JP",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "奈良新聞",
        "奈良新聞 news",
        "奈良新聞 Japan"
      ],
      summary: "息子装い女性から150万円詐取疑い 21歳「指示役」を逮捕（FNNプライムオンライン（フジテレビ系））",
      detail: "息子装い女性から150万円詐取疑い 21歳「指示役」を逮捕（FNNプライムオンライン（フジテレビ系））\n奈良新聞 is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "詐欺",
      slug: "jp-詐欺-2026-05-28",
      traffic: "200+",
      description: "詐欺被害金の追跡 警察と銀行協定",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/pickup/6582001",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRBFlwDF6WUWY8NS4GluEvplxKn1SLIqkXyIDVxD2CHtUqK1ZNTguGQSvx6Ppk",
      country: "JP",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "詐欺",
        "詐欺 news",
        "詐欺 Japan"
      ],
      summary: "詐欺被害金の追跡 警察と銀行協定",
      detail: "詐欺被害金の追跡 警察と銀行協定\n詐欺 is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "浜辺美波",
      slug: "jp-浜辺美波-2026-05-28",
      traffic: "100+",
      description: "映画『ほどなく、お別れです』Blu-ray&DVDが2026年8月19日発売 オンライン期間限定：ポイント20％還元",
      source: "タワーレコード オンライン",
      sourceUrl: "https://tower.jp/article/feature_item/2026/05/28/2501",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTcIH31GuaWVujM5UhUT0-XEUbuddL5fXbr0D15toAAXJeuuKVjmP8oGgK_hLo",
      country: "JP",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "浜辺美波",
        "浜辺美波 news",
        "浜辺美波 Japan"
      ],
      summary: "映画『ほどなく、お別れです』Blu-ray&DVDが2026年8月19日発売 オンライン期間限定：ポイント20％還元",
      detail: "映画『ほどなく、お別れです』Blu-ray&DVDが2026年8月19日発売 オンライン期間限定：ポイント20％還元\n浜辺美波 is seeing increased search interest in Japan.\nSource: タワーレコード オンライン.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "チャンピオンズリーグ",
      slug: "jp-チャンピオンズリーグ-2026-05-28",
      traffic: "500+",
      description: "悲劇から20年――アーセナル伝説名将ヴェンゲル、悲願のCL制覇を支持「歴史の集大成」「プレミアを安定して支配する時が来た」（SOCCER DIGEST Web）",
      source: "Yahoo!ニュース",
      sourceUrl: "https://news.yahoo.co.jp/articles/b1b8de3a1937a48a3424d764bb71f19bf758f962",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQLOYsy3xyxedstlQcfsU-Viz61XddpGsWrqofAaMAehKPUCQ3Noc7hWtfaIKI",
      country: "JP",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "チャンピオンズリーグ",
        "チャンピオンズリーグ news",
        "チャンピオンズリーグ Japan"
      ],
      summary: "悲劇から20年――アーセナル伝説名将ヴェンゲル、悲願のCL制覇を支持「歴史の集大成」「プレミアを安定して支配する時が来た」（SOCCER DIGEST Web）",
      detail: "悲劇から20年――アーセナル伝説名将ヴェンゲル、悲願のCL制覇を支持「歴史の集大成」「プレミアを安定して支配する時が来た」（SOCCER DIGEST Web）\nチャンピオンズリーグ is seeing increased search interest in Japan.\nSource: Yahoo!ニュース.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AU: [
    {
      title: "claude lemieux",
      slug: "au-claude-lemieux-2026-05-28",
      traffic: "100+",
      description: "4-time Stanley Cup champion Claude Lemieux dies at 60",
      source: "ESPN",
      sourceUrl: "https://www.espn.com.au/nhl/story/_/id/48901936/4-stanley-cup-champion-claude-lemieux-dies-60",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRjD-xwudLm6gLy1I2hSrRyDrhDi-8Tt-w7SX9pu_iDHjYiiLIq_u6rWO8fRRI",
      country: "AU",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "claude lemieux",
        "claude lemieux news",
        "claude lemieux Australia"
      ],
      summary: "4-time Stanley Cup champion Claude Lemieux dies at 60",
      detail: "4-time Stanley Cup champion Claude Lemieux dies at 60\nclaude lemieux is seeing increased search interest in Australia.\nSource: ESPN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "al jazeera",
      slug: "au-al-jazeera-2026-05-28",
      traffic: "200+",
      description: "Live updates: US and Iran reach tentative agreement, but deal still needs Trump’s sign-off",
      source: "CNN",
      sourceUrl: "https://www.cnn.com/2026/05/28/world/live-news/iran-war-us-news",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSmVd2w3T7aQiB-mLFGPA0o4PtQq7zJPkTdeq5hKbCCx_Wr6YbZRNqU_GN1BvY",
      country: "AU",
      date: "2026-05-28",
      pubTime: "47m ago",
      relatedQueries: [
        "al jazeera",
        "al jazeera news",
        "al jazeera Australia"
      ],
      summary: "Live updates: US and Iran reach tentative agreement, but deal still needs Trump’s sign-off",
      detail: "Live updates: US and Iran reach tentative agreement, but deal still needs Trump’s sign-off\nal jazeera is seeing increased search interest in Australia.\nSource: CNN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "robbie mortimer national anthem",
      slug: "au-robbie-mortimer-national-anthem-2026-05-28",
      traffic: "500+",
      description: "Fans missed the point of Origin anthem",
      source: "News.com.au",
      sourceUrl: "https://www.news.com.au/sport/nrl/fans-got-it-all-wrong-about-murdered-national-anthem-before-state-of-origin-game-1/news-story/53a6a561bec9619bdb5beb323564e358",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRTzcX7BZ-WzRaYbTfSyO5Ih_ul6ANiZkjYZf1PqleFgCccbnXmDQ8MI5NXoEE",
      country: "AU",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "robbie mortimer national anthem",
        "robbie mortimer national anthem news",
        "robbie mortimer national anthem Australia"
      ],
      summary: "Fans missed the point of Origin anthem",
      detail: "Fans missed the point of Origin anthem\nrobbie mortimer national anthem is seeing increased search interest in Australia.\nSource: News.com.au.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "liv golf",
      slug: "au-liv-golf-2026-05-28",
      traffic: "100+",
      description: "DeChambeau makes flying start to share LIV lead",
      source: "The Canberra Times",
      sourceUrl: "https://www.canberratimes.com.au/story/9256043/dechambeau-makes-flying-start-to-share-liv-lead/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOTejuAeC6tzYeuSlRLl0KzFJIR-ejwNmOBUYg7-G3M6cM8uEs87xqMDhHiZg",
      country: "AU",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "liv golf",
        "liv golf news",
        "liv golf Australia"
      ],
      summary: "DeChambeau makes flying start to share LIV lead",
      detail: "DeChambeau makes flying start to share LIV lead\nliv golf is seeing increased search interest in Australia.\nSource: The Canberra Times.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "weather gold coast",
      slug: "au-weather-gold-coast-2026-05-28",
      traffic: "200+",
      description: "Gold Coast set to break 28-year rain record",
      source: "Gold Coast Bulletin",
      sourceUrl: "https://www.goldcoastbulletin.com.au/news/gold-coast/gold-coast-to-break-may-rainfall-record-with-triple-monthly-average/news-story/eda0e143be49892616a2cd663d726dc0",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST7gpDdnwx1qi0fJuWZVKJ7j0ru5zK1bFT-UU7d9wUjpD8g7K7fN1DAOxK3H8",
      country: "AU",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "weather gold coast",
        "weather gold coast news",
        "weather gold coast Australia"
      ],
      summary: "Gold Coast set to break 28-year rain record",
      detail: "Gold Coast set to break 28-year rain record\nweather gold coast is seeing increased search interest in Australia.\nSource: Gold Coast Bulletin.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  KR: [
    {
      title: "부모",
      slug: "kr-부모-2026-05-28",
      traffic: "500+",
      description: "[단독] 3040 캥거루족 8만명…은퇴한 부모는 또 일터 나간다",
      source: "Daum",
      sourceUrl: "https://v.daum.net/v/20260529050317149",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTDFId-LfaQvz5swsmf0RxfTnTJbn908AcJ-ihsI3WLkM8RmLxmspa3XYjVTmY",
      country: "KR",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "부모",
        "부모 news",
        "부모 South Korea"
      ],
      summary: "[단독] 3040 캥거루족 8만명…은퇴한 부모는 또 일터 나간다",
      detail: "[단독] 3040 캥거루족 8만명…은퇴한 부모는 또 일터 나간다\n부모 is seeing increased search interest in South Korea.\nSource: Daum.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "유조선",
      slug: "kr-유조선-2026-05-28",
      traffic: "500+",
      description: "바다 위 유조선 나란히 묶더니…이란산 원유 '해상 무법지' 환적",
      source: "SBS 뉴스",
      sourceUrl: "https://news.sbs.co.kr/news/endPage.do?news_id=N1008584640",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRht7Cfgm1Nqgu1SSuABO7_x2stqCwb7hU5bH-_BFkkyBGOutT19bpl4T1fwJs",
      country: "KR",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "유조선",
        "유조선 news",
        "유조선 South Korea"
      ],
      summary: "바다 위 유조선 나란히 묶더니…이란산 원유 '해상 무법지' 환적",
      detail: "바다 위 유조선 나란히 묶더니…이란산 원유 '해상 무법지' 환적\n유조선 is seeing increased search interest in South Korea.\nSource: SBS 뉴스.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "돌풍",
      slug: "kr-돌풍-2026-05-28",
      traffic: "200+",
      description: "[주간! 대중문화] 대세배우 변우석, 허당미로 ‘예능 킹’ 도전…배우 자리매김 B1A4 출신 ‘진영’",
      source: "KBS 뉴스",
      sourceUrl: "https://news.kbs.co.kr/news/view.do?ncd=8571281",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSLJmrMSlbPis-7MzZrC4d7GMmFVL2CJTfxkB6Qq-ijqwJlwgh6w7EmtfIQf2g",
      country: "KR",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "돌풍",
        "돌풍 news",
        "돌풍 South Korea"
      ],
      summary: "[주간! 대중문화] 대세배우 변우석, 허당미로 ‘예능 킹’ 도전…배우 자리매김 B1A4 출신 ‘진영’",
      detail: "[주간! 대중문화] 대세배우 변우석, 허당미로 ‘예능 킹’ 도전…배우 자리매김 B1A4 출신 ‘진영’\n돌풍 is seeing increased search interest in South Korea.\nSource: KBS 뉴스.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "조태용",
      slug: "kr-조태용-2026-05-28",
      traffic: "200+",
      description: "특검, '계엄 정당화 메시지' 조태용 前국정원장 내달 1일 소환",
      source: "연합뉴스",
      sourceUrl: "https://www.yna.co.kr/view/AKR20260528125500004",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTGw_4QofLdW-Owr6XsrrPSeKoeXTS5DmwrNppEcKyjiAf1vH8uTMLLvRE67E",
      country: "KR",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "조태용",
        "조태용 news",
        "조태용 South Korea"
      ],
      summary: "특검, '계엄 정당화 메시지' 조태용 前국정원장 내달 1일 소환",
      detail: "특검, '계엄 정당화 메시지' 조태용 前국정원장 내달 1일 소환\n조태용 is seeing increased search interest in South Korea.\nSource: 연합뉴스.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "안정환",
      slug: "kr-안정환-2026-05-28",
      traffic: "200+",
      description: "“꼬마가 이렇게 크다니”…안정환·이혜원 딸 리원, 뉴욕대 졸업",
      source: "동아일보",
      sourceUrl: "https://www.donga.com/news/Culture/article/all/20260528/134012691/2",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI0Xd1qrFmoP-OTuRGVApUWrTX64MH9CYhPeVrS54tx8bjN0LXA0LZ2f8TJ_Y",
      country: "KR",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "안정환",
        "안정환 news",
        "안정환 South Korea"
      ],
      summary: "“꼬마가 이렇게 크다니”…안정환·이혜원 딸 리원, 뉴욕대 졸업",
      detail: "“꼬마가 이렇게 크다니”…안정환·이혜원 딸 리원, 뉴욕대 졸업\n안정환 is seeing increased search interest in South Korea.\nSource: 동아일보.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  BR: [
    {
      title: "declaração mei",
      slug: "br-declarao-mei-2026-05-28",
      traffic: "2000+",
      description: "MEI: errou a declaração anual? Veja como retificar",
      source: "G1",
      sourceUrl: "https://g1.globo.com/empreendedorismo/guia-do-empreendedor/noticia/2026/05/28/mei-errou-a-declaracao-anual-veja-como-retificar.ghtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRrDHO1ePchlBfuzOBQkdjUKoWtLd-uTe-7ngY3Rmba5ywq0XJicvwTtLchWDg",
      country: "BR",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "declaração mei",
        "declaração mei news",
        "declaração mei Brazil"
      ],
      summary: "MEI: errou a declaração anual? Veja como retificar",
      detail: "MEI: errou a declaração anual? Veja como retificar\ndeclaração mei is seeing increased search interest in Brazil.\nSource: G1.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "militar",
      slug: "br-militar-2026-05-28",
      traffic: "200+",
      description: "Marinha pagará militar trans obrigada a usar cabelo e roupa masculina",
      source: "Migalhas",
      sourceUrl: "https://www.migalhas.com.br/quentes/456989/marinha-pagara-militar-trans-obrigada-a-usar-cabelo-e-roupa-masculina",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT-_cqBwjRAQmGnC15lHx3LHtTN2-U609SeoqdXe5LXZH0LZRFMOP02ufpCG2k",
      country: "BR",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "militar",
        "militar news",
        "militar Brazil"
      ],
      summary: "Marinha pagará militar trans obrigada a usar cabelo e roupa masculina",
      detail: "Marinha pagará militar trans obrigada a usar cabelo e roupa masculina\nmilitar is seeing increased search interest in Brazil.\nSource: Migalhas.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "bolsa família 2026",
      slug: "br-bolsa-famlia-2026-2026-05-28",
      traffic: "200+",
      description: "O que Luciano Huck disse sobre o Bolsa Família e por que seu nome também apareceu ligado a Vorcaro",
      source: "Gazeta do Povo",
      sourceUrl: "https://www.gazetadopovo.com.br/republica/o-que-luciano-huck-disse-sobre-o-bolsa-familia-e-por-que-seu-nome-tambem-apareceu-ligado-a-vorcaro/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSnWdl5DZWFmmdn1VL-T7FL_PlbVToqSyAkvCp1q_8wrKAJTYR6CVGBLvLM4O4",
      country: "BR",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "bolsa família 2026",
        "bolsa família 2026 news",
        "bolsa família 2026 Brazil"
      ],
      summary: "O que Luciano Huck disse sobre o Bolsa Família e por que seu nome também apareceu ligado a Vorcaro",
      detail: "O que Luciano Huck disse sobre o Bolsa Família e por que seu nome também apareceu ligado a Vorcaro\nbolsa família 2026 is seeing increased search interest in Brazil.\nSource: Gazeta do Povo.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jfk jr",
      slug: "br-jfk-jr-2026-05-28",
      traffic: "100+",
      description: "Madonna revela que John F. Kennedy Jr. foi o melhor sexo de sua vida",
      source: "UOL",
      sourceUrl: "https://www.uol.com.br/splash/noticias/2026/05/28/madonna-diz-que-jfk-jr-foi-seu-melhor-sexo-e-cita-prevencao-ao-hiv.ghtm",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT2K7gkYK6p7YB3uc7IPPqbzsIgz21LXgEGnFus4Aww-7-GKFZzUhVP0pR0_jM",
      country: "BR",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "jfk jr",
        "jfk jr news",
        "jfk jr Brazil"
      ],
      summary: "Madonna revela que John F. Kennedy Jr. foi o melhor sexo de sua vida",
      detail: "Madonna revela que John F. Kennedy Jr. foi o melhor sexo de sua vida\njfk jr is seeing increased search interest in Brazil.\nSource: UOL.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "superior tribunal de justiça",
      slug: "br-superior-tribunal-de-justia-2026-05-28",
      traffic: "100+",
      description: "Zanin dá mais 60 dias de prazo para PF investigar novas frentes de suposto esquema de venda de sentenças no STJ",
      source: "O GLOBO",
      sourceUrl: "https://oglobo.globo.com/politica/noticia/2026/05/28/zanin-da-mais-60-dias-de-prazo-para-pf-investigar-novas-frentes-de-suposto-esquema-de-venda-de-sentencas-no-stj.ghtml",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSLQdWl2vTkB4zs3jEBUGxJeYNirYcXwmFs60djqOJFT3pH6lFxUVCvknJCB2o",
      country: "BR",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "superior tribunal de justiça",
        "superior tribunal de justiça news",
        "superior tribunal de justiça Brazil"
      ],
      summary: "Zanin dá mais 60 dias de prazo para PF investigar novas frentes de suposto esquema de venda de sentenças no STJ",
      detail: "Zanin dá mais 60 dias de prazo para PF investigar novas frentes de suposto esquema de venda de sentenças no STJ\nsuperior tribunal de justiça is seeing increased search interest in Brazil.\nSource: O GLOBO.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IN: [
    {
      title: "iran us news",
      slug: "in-iran-us-news-2026-05-28",
      traffic: "5000+",
      description: "US and Iran reach tentative deal to extend ceasefire, US officials say",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c87qng40wz9o",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSwcDw409TZ7Imdf_JnYPlKu1sef_ihstSEt_Ij7cFhrLoNCCPrZdGBqgHBAhQ",
      country: "IN",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "iran us news",
        "iran us news news",
        "iran us news India"
      ],
      summary: "US and Iran reach tentative deal to extend ceasefire, US officials say",
      detail: "US and Iran reach tentative deal to extend ceasefire, US officials say\niran us news is seeing increased search interest in India.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "sec",
      slug: "in-sec-2026-05-28",
      traffic: "100+",
      description: "Evercore ISI raises Scorpio Tankers stock price target on fleet moves By Investing.com",
      source: "Investing.com South Africa",
      sourceUrl: "https://za.investing.com/news/stock-market-news/evercore-isi-raises-scorpio-tankers-stock-price-target-on-fleet-moves-93CH-4302280",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8IwWJEEQmXa-nHLXtRf1U6E7SwvQ8JO5Qfjujn9DoaLKgDOzCaXpKmf1NlAA",
      country: "IN",
      date: "2026-05-28",
      pubTime: "57m ago",
      relatedQueries: [
        "sec",
        "sec news",
        "sec India"
      ],
      summary: "Evercore ISI raises Scorpio Tankers stock price target on fleet moves By Investing.com",
      detail: "Evercore ISI raises Scorpio Tankers stock price target on fleet moves By Investing.com\nsec is seeing increased search interest in India.\nSource: Investing.com South Africa.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "england",
      slug: "in-england-2026-05-28",
      traffic: "100+",
      description: "Anthony Gordon arrives in Barcelona ahead of €70m switch from Newcastle",
      source: "ESPN India",
      sourceUrl: "https://www.espn.in/football/story/_/id/48898128/anthony-gordon-arrives-barcelona-ahead-70m-switch-newcastle",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQVYU85TZRpduuFtuWgvUsYc_VUPnRrxBMyx83NLCDApP8btVKR2Oxa2cPTdO0",
      country: "IN",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "england",
        "england news",
        "england India"
      ],
      summary: "Anthony Gordon arrives in Barcelona ahead of €70m switch from Newcastle",
      detail: "Anthony Gordon arrives in Barcelona ahead of €70m switch from Newcastle\nengland is seeing increased search interest in India.\nSource: ESPN India.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "hrithik roshan",
      slug: "in-hrithik-roshan-2026-05-28",
      traffic: "100+",
      description: "Hrithik Roshan To Enter Jailer 2 After Shah Rukh Khan Exit Buzz?",
      source: "The Times of India",
      sourceUrl: "https://timesofindia.indiatimes.com/videos/etimes/bollywood/hrithik-roshan-to-enter-jailer-2-after-shah-rukh-khan-exit-buzz/videoshow/131367167.cms",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRX2W7gb1KqhAvyg85pq7Lwk1CQj9yH2ZBt0zx1PEDt1XOvPwYuNInF_PVhbKk",
      country: "IN",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "hrithik roshan",
        "hrithik roshan news",
        "hrithik roshan India"
      ],
      summary: "Hrithik Roshan To Enter Jailer 2 After Shah Rukh Khan Exit Buzz?",
      detail: "Hrithik Roshan To Enter Jailer 2 After Shah Rukh Khan Exit Buzz?\nhrithik roshan is seeing increased search interest in India.\nSource: The Times of India.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  ES: [
    {
      title: "cada dia nace un listo",
      slug: "es-cada-dia-nace-un-listo-2026-05-28",
      traffic: "200+",
      description: "Arantxa Echevarría dirige 'Cada día nace un listo': \"Estamos en una sociedad política absurda\"",
      source: "Hoy",
      sourceUrl: "https://www.hoy.es/culturas/arantxa-echevarra-dirige-nace-listo-sociedad-poltica-20260528165514-vi.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTb5B8xgspNbHrfTf_xmXawe9P5cqZuRNU8rUifD10XsONeqssJFfqDFbw2ufs",
      country: "ES",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "cada dia nace un listo",
        "cada dia nace un listo news",
        "cada dia nace un listo Spain"
      ],
      summary: "Arantxa Echevarría dirige 'Cada día nace un listo': \"Estamos en una sociedad política absurda\"",
      detail: "Arantxa Echevarría dirige 'Cada día nace un listo': \"Estamos en una sociedad política absurda\"\ncada dia nace un listo is seeing increased search interest in Spain.\nSource: Hoy.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "mallorca confidencial",
      slug: "es-mallorca-confidencial-2026-05-28",
      traffic: "100+",
      description: "Lolita Flores: \"Como De Niro, por un papel sería capaz de adelgazar, engordar, cortarme el pelo...\"",
      source: "RTVE.es",
      sourceUrl: "https://www.rtve.es/noticias/20260525/lolita-flores-como-niro-por-papel-seria-capaz-adelgazar-engordar-cortarme-pelo/17084204.shtml",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSPaXBGa5BmPJOLU7WKBfjtIptbf9nHeyoCpA6hW1i166JrOJrEJ7vMbpbOykM",
      country: "ES",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "mallorca confidencial",
        "mallorca confidencial news",
        "mallorca confidencial Spain"
      ],
      summary: "Lolita Flores: \"Como De Niro, por un papel sería capaz de adelgazar, engordar, cortarme el pelo...\"",
      detail: "Lolita Flores: \"Como De Niro, por un papel sería capaz de adelgazar, engordar, cortarme el pelo...\"\nmallorca confidencial is seeing increased search interest in Spain.\nSource: RTVE.es.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "bonoloto 28 mayo 2026",
      slug: "es-bonoloto-28-mayo-2026-2026-05-28",
      traffic: "200+",
      description: "Bonoloto: comprobar resultado del sorteo del miércoles 27 de mayo de 2026",
      source: "El Mundo",
      sourceUrl: "https://www.elmundo.es/loterias/2026/05/27/6a1749c4e4d4d8612b8b459b.html",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6ikO0cB9fjGgXXVLnSlsXQm6vKj5XS5A8SEUybTsJFqDn4BRwM7YsmFlnXBo",
      country: "ES",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "bonoloto 28 mayo 2026",
        "bonoloto 28 mayo 2026 news",
        "bonoloto 28 mayo 2026 Spain"
      ],
      summary: "Bonoloto: comprobar resultado del sorteo del miércoles 27 de mayo de 2026",
      detail: "Bonoloto: comprobar resultado del sorteo del miércoles 27 de mayo de 2026\nbonoloto 28 mayo 2026 is seeing increased search interest in Spain.\nSource: El Mundo.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jupol",
      slug: "es-jupol-2026-05-28",
      traffic: "200+",
      description: "“Dale lo de Jesús”: el comisario de Barajas y la red que se investiga en paralelo al ‘caso Plus Ultra’",
      source: "infoLibre",
      sourceUrl: "https://www.infolibre.es/politica/dale-jesus-comisario-barajas-red-investiga-paralelo-caso-plus-ultra_1_2199899.html",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRJOHe-LQ9t2ssOy-PPSouVrMCtrutujcx2KYc1JvXO75PpYBHPuwJvrFCBWqE",
      country: "ES",
      date: "2026-05-28",
      pubTime: "27m ago",
      relatedQueries: [
        "jupol",
        "jupol news",
        "jupol Spain"
      ],
      summary: "“Dale lo de Jesús”: el comisario de Barajas y la red que se investiga en paralelo al ‘caso Plus Ultra’",
      detail: "“Dale lo de Jesús”: el comisario de Barajas y la red que se investiga en paralelo al ‘caso Plus Ultra’\njupol is seeing increased search interest in Spain.\nSource: infoLibre.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "cadena de supermercados",
      slug: "es-cadena-de-supermercados-2026-05-28",
      traffic: "200+",
      description: "Juan Roig tiene la fecha de la llegada a todas las tiendas de Mercadona del mayor éxito de los últimos años de la compañía",
      source: "El HuffPost",
      sourceUrl: "https://www.huffingtonpost.es/economia/juan-roig-fecha-llegada-todas-tiendas-mercadona-mayor-exito-ultimosnos-compania-rpc-f202605.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSHIcfIy_fElZiL9h83uSeiQFOCc9LO7itIkQvVrZz6mNp2x_XRgOOKN6O_WlM",
      country: "ES",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "cadena de supermercados",
        "cadena de supermercados news",
        "cadena de supermercados Spain"
      ],
      summary: "Juan Roig tiene la fecha de la llegada a todas las tiendas de Mercadona del mayor éxito de los últimos años de la compañía",
      detail: "Juan Roig tiene la fecha de la llegada a todas las tiendas de Mercadona del mayor éxito de los últimos años de la compañía\ncadena de supermercados is seeing increased search interest in Spain.\nSource: El HuffPost.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  CH: [
    {
      title: "lukas bärfuss",
      slug: "ch-lukas-brfuss-2026-05-28",
      traffic: "200+",
      description: "Lukas Bärfuss: «Ich bin der Überlebende meiner Kindheit»",
      source: "SRF",
      sourceUrl: "https://www.srf.ch/play/tv/gredig-direkt/video/lukas-baerfuss-ich-bin-der-ueberlebende-meiner-kindheit?urn=urn:srf:video:3e425f07-5a68-4e8e-9d00-1de9a74fbd1d",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTV6R7VIswZ5HD3rECttDCjJbQrOHeeHNrRNEWw1z4eVyAY-iaDW9ULzTrLia4",
      country: "CH",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "lukas bärfuss",
        "lukas bärfuss news",
        "lukas bärfuss Switzerland"
      ],
      summary: "Lukas Bärfuss: «Ich bin der Überlebende meiner Kindheit»",
      detail: "Lukas Bärfuss: «Ich bin der Überlebende meiner Kindheit»\nlukas bärfuss is seeing increased search interest in Switzerland.\nSource: SRF.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "hockey",
      slug: "ch-hockey-2026-05-28",
      traffic: "100+",
      description: "EHC Biel extends with Jamie Villard, signs two youngsters to pro contracts",
      source: "swisshockeynews.ch",
      sourceUrl: "https://swisshockeynews.ch/en/shn/men/swiss-hockey/nl/ehc-biel-extends-with-jamie-villard-signs-two-youngsters-to-pro-contracts",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRU9Xzdk9ZFrUDmIyUvZR-AuVcNti65Dx2uwuiFFMubMRjVeSEd9HVkCr-QaqU",
      country: "CH",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "hockey",
        "hockey news",
        "hockey Switzerland"
      ],
      summary: "EHC Biel extends with Jamie Villard, signs two youngsters to pro contracts",
      detail: "EHC Biel extends with Jamie Villard, signs two youngsters to pro contracts\nhockey is seeing increased search interest in Switzerland.\nSource: swisshockeynews.ch.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "spielplan eishockey wm 2026",
      slug: "ch-spielplan-eishockey-wm-2026-2026-05-28",
      traffic: "1000+",
      description: "Kanada schaltet Titelverteidiger aus und steht im Halbfinal",
      source: "Blick",
      sourceUrl: "https://www.blick.ch/sport/eishockey/wm/weltmeisterschaft-kanada-usa-28-05-2026-id21982773.html",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ19LpjAcdKtf6JICPQll9ie7oqZp5SnCoBCaVYVbaDc9YbcEIX84CMOmv9Q_8",
      country: "CH",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "spielplan eishockey wm 2026",
        "spielplan eishockey wm 2026 news",
        "spielplan eishockey wm 2026 Switzerland"
      ],
      summary: "Kanada schaltet Titelverteidiger aus und steht im Halbfinal",
      detail: "Kanada schaltet Titelverteidiger aus und steht im Halbfinal\nspielplan eishockey wm 2026 is seeing increased search interest in Switzerland.\nSource: Blick.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "genoni",
      slug: "ch-genoni-2026-05-28",
      traffic: "500+",
      description: "Segui il periodo centrale di Svizzera-Svezia in diretta alla RSI",
      source: "RSI Radiotelevisione svizzera",
      sourceUrl: "https://www.rsi.ch/sport/hockey/Segui-il-periodo-centrale-di-Svizzera-Svezia-in-diretta-alla-RSI--3778198.html",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR5PJ5FyDSrwlPzgO-wwTv85NYJykwV4ssl53TQcB0RcZj4pD2_Ga7NMJxsaO8",
      country: "CH",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "genoni",
        "genoni news",
        "genoni Switzerland"
      ],
      summary: "Segui il periodo centrale di Svizzera-Svezia in diretta alla RSI",
      detail: "Segui il periodo centrale di Svizzera-Svezia in diretta alla RSI\ngenoni is seeing increased search interest in Switzerland.\nSource: RSI Radiotelevisione svizzera.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "thürkauf",
      slug: "ch-thrkauf-2026-05-28",
      traffic: "500+",
      description: "Kalalulu und Baume-Schneider? – die Nati-Spieler testen ihr Allgemeinwissen",
      source: "Watson",
      sourceUrl: "https://www.watson.ch/videos/!51698",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRCuITs-o49h-gd8AS960954-DQBgaYwmEMnrWOmihGJXztXO1XZB_VwNPOYrM",
      country: "CH",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "thürkauf",
        "thürkauf news",
        "thürkauf Switzerland"
      ],
      summary: "Kalalulu und Baume-Schneider? – die Nati-Spieler testen ihr Allgemeinwissen",
      detail: "Kalalulu und Baume-Schneider? – die Nati-Spieler testen ihr Allgemeinwissen\nthürkauf is seeing increased search interest in Switzerland.\nSource: Watson.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  MX: [
    {
      title: "palmeiras vs junior",
      slug: "mx-palmeiras-vs-junior-2026-05-28",
      traffic: "100+",
      description: "Palmeiras vs Junior EN VIVO Copa Libertadores Jornada 6",
      source: "RÉCORD",
      sourceUrl: "https://www.record.com.mx/futbol/partido/palmeiras-junior-fc-8431009/cobertura-en-vivo",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQwVmx9pNtK4Qr359iYP1xJqtkd7Z_GXmijVtHnWvpWtcBsqqwdExEDfRDve5k",
      country: "MX",
      date: "2026-05-28",
      pubTime: "7m ago",
      relatedQueries: [
        "palmeiras vs junior",
        "palmeiras vs junior news",
        "palmeiras vs junior Mexico"
      ],
      summary: "Palmeiras vs Junior EN VIVO Copa Libertadores Jornada 6",
      detail: "Palmeiras vs Junior EN VIVO Copa Libertadores Jornada 6\npalmeiras vs junior is seeing increased search interest in Mexico.\nSource: RÉCORD.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "rafael campos",
      slug: "mx-rafael-campos-2026-05-28",
      traffic: "100+",
      description: "Muere integrante de ‘María de Todos los Ángeles’; Mara Escalante confirma triste pérdida",
      source: "RÉCORD",
      sourceUrl: "https://www.record.com.mx/historia/muere-integrante-de-maria-de-todos-los-angeles-mara-escalante-confirma-triste-perdida-2026052818265718668",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRActyGx8iHCebx21MH91XgKjHw7EvjKAc9c0Wxp0JPQH64OsjjoXlM0F1RSg4",
      country: "MX",
      date: "2026-05-28",
      pubTime: "47m ago",
      relatedQueries: [
        "rafael campos",
        "rafael campos news",
        "rafael campos Mexico"
      ],
      summary: "Muere integrante de ‘María de Todos los Ángeles’; Mara Escalante confirma triste pérdida",
      detail: "Muere integrante de ‘María de Todos los Ángeles’; Mara Escalante confirma triste pérdida\nrafael campos is seeing increased search interest in Mexico.\nSource: RÉCORD.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "semana nacional de salud publica 2026",
      slug: "mx-semana-nacional-de-salud-publica-2026-2026-05-28",
      traffic: "100+",
      description: "Salud Colima llama a municipios a reforzar acciones preventivas durante la temporada de lluvias y huracanes 2026",
      source: "Servicios de Salud del Estado de Colima",
      sourceUrl: "https://saludcolima.gob.mx/noticia.php?id=8959",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8aHL0T-pXywyKl9XhNLPZYXkQkmGaRPA2aCCoawODwrPfrjNvsHDAg1YyP0w",
      country: "MX",
      date: "2026-05-28",
      pubTime: "57m ago",
      relatedQueries: [
        "semana nacional de salud publica 2026",
        "semana nacional de salud publica 2026 news",
        "semana nacional de salud publica 2026 Mexico"
      ],
      summary: "Salud Colima llama a municipios a reforzar acciones preventivas durante la temporada de lluvias y huracanes 2026",
      detail: "Salud Colima llama a municipios a reforzar acciones preventivas durante la temporada de lluvias y huracanes 2026\nsemana nacional de salud publica 2026 is seeing increased search interest in Mexico.\nSource: Servicios de Salud del Estado de Colima.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  NO: [
    {
      title: "sofie marhaug",
      slug: "no-sofie-marhaug-2026-05-28",
      traffic: "200+",
      description: "Rødt-topp krever at staten trekker milliardlån til KI-giganten Nscale",
      source: "NRK",
      sourceUrl: "https://www.nrk.no/nordland/rodt-topp-krever-at-staten-trekker-milliardlan-til-ki-giganten-nscale-1.17898238",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQUX5yqJJ5zYtVFRrQ-HVT4yyalF7xIemBp9jvpI9a6h6jYN17Dxb46U9ACHSI",
      country: "NO",
      date: "2026-05-28",
      pubTime: "37m ago",
      relatedQueries: [
        "sofie marhaug",
        "sofie marhaug news",
        "sofie marhaug Norway"
      ],
      summary: "Rødt-topp krever at staten trekker milliardlån til KI-giganten Nscale",
      detail: "Rødt-topp krever at staten trekker milliardlån til KI-giganten Nscale\nsofie marhaug is seeing increased search interest in Norway.\nSource: NRK.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "koblar",
      slug: "no-koblar-2026-05-28",
      traffic: "1000+",
      description: "Hockey-sensasjonen Tinus (18): –⁠ Vi sa han var litt gal",
      source: "VG",
      sourceUrl: "https://www.vg.no/sport/i/XM5ann/tinus-luc-koblar-dette-er-historien-om-norges-hockeytalent",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0mXnsK-4x9mr6bxeM3bckSus9jfj_0lHcvZT-TIIH9M9bSL_bKu_16PYOviI",
      country: "NO",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "koblar",
        "koblar news",
        "koblar Norway"
      ],
      summary: "Hockey-sensasjonen Tinus (18): –⁠ Vi sa han var litt gal",
      detail: "Hockey-sensasjonen Tinus (18): –⁠ Vi sa han var litt gal\nkoblar is seeing increased search interest in Norway.\nSource: VG.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "nordlandsbanen",
      slug: "no-nordlandsbanen-2026-05-28",
      traffic: "100+",
      description: "Faren omkom på Nordlandsbanen: – Det som kommer frem i rapporten er jo krise",
      source: "NRK",
      sourceUrl: "https://www.nrk.no/nordland/rolf-henry-omkom-pa-nordlandsbanen.-na-far-bane-nor-kritikk-for-sikkerheten-1.17898920",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3bwDD3i6a5_X4reA9JJFNXTsGI5uBu0O4pwJJie-5UKWsUvuZ-0ayBI1UPKA",
      country: "NO",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "nordlandsbanen",
        "nordlandsbanen news",
        "nordlandsbanen Norway"
      ],
      summary: "Faren omkom på Nordlandsbanen: – Det som kommer frem i rapporten er jo krise",
      detail: "Faren omkom på Nordlandsbanen: – Det som kommer frem i rapporten er jo krise\nnordlandsbanen is seeing increased search interest in Norway.\nSource: NRK.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  BE: [
    {
      title: "de slimste mens ter wereld",
      slug: "be-de-slimste-mens-ter-wereld-2026-05-28",
      traffic: "100+",
      description: "Dit zijn de eerste deelnemers van nieuw seizoen ‘De slimste mens ter wereld’: “Na de teleurstelling van vorig jaar, lukt het nu wél!”",
      source: "Nieuwsblad",
      sourceUrl: "https://www.nieuwsblad.be/media-en-cultuur/bv-en-co/dit-zijn-de-eerste-deelnemers-van-nieuw-seizoen-de-slimste-mens-ter-wereld-na-de-teleurstelling-van-vorig-jaar-lukt-het-nu-wel/153752919.html",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3rWTNL3nop2Tl8s9JB_dVv2SfYIPnEi4fRnF7lQyLbQDu63skJ26Mw6tLtQA",
      country: "BE",
      date: "2026-05-28",
      pubTime: "57m ago",
      relatedQueries: [
        "de slimste mens ter wereld",
        "de slimste mens ter wereld news",
        "de slimste mens ter wereld Belgium"
      ],
      summary: "Dit zijn de eerste deelnemers van nieuw seizoen ‘De slimste mens ter wereld’: “Na de teleurstelling van vorig jaar, lukt het nu wél!”",
      detail: "Dit zijn de eerste deelnemers van nieuw seizoen ‘De slimste mens ter wereld’: “Na de teleurstelling van vorig jaar, lukt het nu wél!”\nde slimste mens ter wereld is seeing increased search interest in Belgium.\nSource: Nieuwsblad.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "indexering",
      slug: "be-indexering-2026-05-28",
      traffic: "500+",
      description: "Inflatie stijgt door naar 4,1%: wat betekent dit voor de spilindex, de indexering van je loon en je portemonnee?",
      source: "HLN",
      sourceUrl: "https://www.hln.be/binnenland/inflatie-stijgt-door-naar-4-1-wat-betekent-dit-voor-de-spilindex-de-indexering-van-je-loon-en-je-portemonnee~a7b96b74/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7uzEAfPJ6VGRETWbJpbmeyhO0mCvAUpGPMpqY_MqKRuoKqgpWZ90V5K2c26Q",
      country: "BE",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "indexering",
        "indexering news",
        "indexering Belgium"
      ],
      summary: "Inflatie stijgt door naar 4,1%: wat betekent dit voor de spilindex, de indexering van je loon en je portemonnee?",
      detail: "Inflatie stijgt door naar 4,1%: wat betekent dit voor de spilindex, de indexering van je loon en je portemonnee?\nindexering is seeing increased search interest in Belgium.\nSource: HLN.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "andriy biletsky",
      slug: "be-andriy-biletsky-2026-05-28",
      traffic: "100+",
      description: "Exclusive: Senior Ukrainian commander sees imminent 'turning point' in war",
      source: "Reuters",
      sourceUrl: "https://www.reuters.com/business/aerospace-defense/senior-ukrainian-commander-sees-imminent-turning-point-war-2026-05-27/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQsXUX7hvqAr9EKulloLnGuO66Z7B5S5ywXU1_0xfjHbjKhN0-mjEQuQgI8Ses",
      country: "BE",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "andriy biletsky",
        "andriy biletsky news",
        "andriy biletsky Belgium"
      ],
      summary: "Exclusive: Senior Ukrainian commander sees imminent 'turning point' in war",
      detail: "Exclusive: Senior Ukrainian commander sees imminent 'turning point' in war\nandriy biletsky is seeing increased search interest in Belgium.\nSource: Reuters.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AT: [
    {
      title: "brigittenau",
      slug: "at-brigittenau-2026-05-28",
      traffic: "100+",
      description: "Mann nach Messerangriff in Lebensgefahr",
      source: "wien.ORF.at",
      sourceUrl: "https://wien.orf.at/stories/3356086/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThZoDmn_6yPaMddet8Lr8uFTw5ifgdJ4Kchm2sd4np22JvCzYwCVyU-ATKorY",
      country: "AT",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "brigittenau",
        "brigittenau news",
        "brigittenau Austria"
      ],
      summary: "Mann nach Messerangriff in Lebensgefahr",
      detail: "Mann nach Messerangriff in Lebensgefahr\nbrigittenau is seeing increased search interest in Austria.\nSource: wien.ORF.at.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "helene fischer",
      slug: "at-helene-fischer-2026-05-28",
      traffic: "200+",
      description: "Helene Fischer: „Das möchte ich meinem Publikum nie wieder antun“",
      source: "Kleine Zeitung",
      sourceUrl: "https://www.kleinezeitung.at/artikel/26513644/helene-fischer-das-moechte-ich-meinem-publikum-nie-wieder-antun",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfsi0j9GvAmJ6jW8gUFmvql9k_XteZNg-Em-ZWIulF3t42PByz9J1ffGhi1zM",
      country: "AT",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "helene fischer",
        "helene fischer news",
        "helene fischer Austria"
      ],
      summary: "Helene Fischer: „Das möchte ich meinem Publikum nie wieder antun“",
      detail: "Helene Fischer: „Das möchte ich meinem Publikum nie wieder antun“\nhelene fischer is seeing increased search interest in Austria.\nSource: Kleine Zeitung.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  IE: [
    {
      title: "heimir hallgrímsson",
      slug: "ie-heimir-hallgrmsson-2026-05-28",
      traffic: "200+",
      description: "'Israel games issue should have been dealt with above us'",
      source: "RTE.ie",
      sourceUrl: "https://www.rte.ie/sport/soccer/2026/0527/1575521-israel-games-issue-should-have-been-dealt-with-above-us/",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJAQH2NyH3xT2ztgtGmXqfoauok5C_Ej_nirfzdO2d_8iXYSzTvPUtsN_lrD8",
      country: "IE",
      date: "2026-05-28",
      pubTime: "17m ago",
      relatedQueries: [
        "heimir hallgrímsson",
        "heimir hallgrímsson news",
        "heimir hallgrímsson Ireland"
      ],
      summary: "'Israel games issue should have been dealt with above us'",
      detail: "'Israel games issue should have been dealt with above us'\nheimir hallgrímsson is seeing increased search interest in Ireland.\nSource: RTE.ie.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "jaden umeh",
      slug: "ie-jaden-umeh-2026-05-28",
      traffic: "1000+",
      description: "'Anything is possible' for Benfica teenager Umeh",
      source: "RTE.ie",
      sourceUrl: "https://www.rte.ie/sport/soccer/2026/0526/1575323-anything-is-possible-for-benfica-teenager-umeh/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRGw0g1Y5Ucusikhh_FhGYGaSgmz2HYTS7ZyHQea_Fier0efwZOL1mjOoBucsE",
      country: "IE",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "jaden umeh",
        "jaden umeh news",
        "jaden umeh Ireland"
      ],
      summary: "'Anything is possible' for Benfica teenager Umeh",
      detail: "'Anything is possible' for Benfica teenager Umeh\njaden umeh is seeing increased search interest in Ireland.\nSource: RTE.ie.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "train",
      slug: "ie-train-2026-05-28",
      traffic: "200+",
      description: "Man arrested after three injured in stabbing at Swiss train station",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/cddpllqv49qo",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTbyBwCMaU4DOGFuPnasjnMCtb3SSu9O58aAuw3HQ7slv8fGENGww-i5lV9yMc",
      country: "IE",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "train",
        "train news",
        "train Ireland"
      ],
      summary: "Man arrested after three injured in stabbing at Swiss train station",
      detail: "Man arrested after three injured in stabbing at Swiss train station\ntrain is seeing increased search interest in Ireland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "italy rome red heat warning",
      slug: "ie-italy-rome-red-heat-warning-2026-05-28",
      traffic: "5000+",
      description: "Italy on red alert as France, Portugal beat May record",
      source: "RTE.ie",
      sourceUrl: "https://www.rte.ie/news/europe/2026/0528/1575774-europe-hot-weather/",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ7aGkYacZYMROkyIPjeYT4GXSc6gWEVTZMW7_896gmLfWHVGg9jfVklvgAxKA",
      country: "IE",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "italy rome red heat warning",
        "italy rome red heat warning news",
        "italy rome red heat warning Ireland"
      ],
      summary: "Italy on red alert as France, Portugal beat May record",
      detail: "Italy on red alert as France, Portugal beat May record\nitaly rome red heat warning is seeing increased search interest in Ireland.\nSource: RTE.ie.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "temu",
      slug: "ie-temu-2026-05-28",
      traffic: "200+",
      description: "EU fines Temu €200m for allowing sale of illegal products",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/articles/c1k2ydn1rz8o",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQXtepOyt0mbGtypCz5QTb8hZBbfVYBOtvGqJV5IMI0af1M1tfruoQViTTwl2U",
      country: "IE",
      date: "2026-05-28",
      pubTime: "3h ago",
      relatedQueries: [
        "temu",
        "temu news",
        "temu Ireland"
      ],
      summary: "EU fines Temu €200m for allowing sale of illegal products",
      detail: "EU fines Temu €200m for allowing sale of illegal products\ntemu is seeing increased search interest in Ireland.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  AE: [
    {
      title: "ireland vs qatar",
      slug: "ae-ireland-vs-qatar-2026-05-28",
      traffic: "1000+",
      description: "International Friendly LIVE: Republic of Ireland vs Qatar - score, text commentary, match stats & head-to-head",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/live/cz02e105m21t",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcStbhA09FUJ2kmtyLfrtE4Xko4y9jYOruU_dUweJZbMAKD-FGoTnRwf5HURDkk",
      country: "AE",
      date: "2026-05-28",
      pubTime: "2h ago",
      relatedQueries: [
        "ireland vs qatar",
        "ireland vs qatar news",
        "ireland vs qatar UAE"
      ],
      summary: "International Friendly LIVE: Republic of Ireland vs Qatar - score, text commentary, match stats & head-to-head",
      detail: "International Friendly LIVE: Republic of Ireland vs Qatar - score, text commentary, match stats & head-to-head\nireland vs qatar is seeing increased search interest in UAE.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "friendlies",
      slug: "ae-friendlies-2026-05-28",
      traffic: "200+",
      description: "World Cup 2026: Injured Brazil forward Neymar could miss start of competition",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/football/articles/cdrp41erye0o",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQfMqEm19tefFMM3c5QN08xVIkgUSpCBosx3nZtjvIcbr0JNGL9QGtvBJ9m1wE",
      country: "AE",
      date: "2026-05-28",
      pubTime: "3h ago",
      relatedQueries: [
        "friendlies",
        "friendlies news",
        "friendlies UAE"
      ],
      summary: "World Cup 2026: Injured Brazil forward Neymar could miss start of competition",
      detail: "World Cup 2026: Injured Brazil forward Neymar could miss start of competition\nfriendlies is seeing increased search interest in UAE.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "مصر ضد روسيا",
      slug: "ae-مصر-ضد-روسيا-2026-05-28",
      traffic: "5000+",
      description: "المنتخب المصري يتخطى نظيره الروسي ضمن تحضيرات كأس العالم",
      source: "البيان",
      sourceUrl: "https://www.albayan.ae/sports/world-cup-2026/1332357",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRmz_0j8rdIw34htc56QZlPNeeeL-Ykg-tv6VOJjRZUsKVnzFpOYx81aeWbz2A",
      country: "AE",
      date: "2026-05-28",
      pubTime: "3h ago",
      relatedQueries: [
        "مصر ضد روسيا",
        "مصر ضد روسيا news",
        "مصر ضد روسيا UAE"
      ],
      summary: "المنتخب المصري يتخطى نظيره الروسي ضمن تحضيرات كأس العالم",
      detail: "المنتخب المصري يتخطى نظيره الروسي ضمن تحضيرات كأس العالم\nمصر ضد روسيا is seeing increased search interest in UAE.\nSource: البيان.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "india women vs england women",
      slug: "ae-india-women-vs-england-women-2026-05-28",
      traffic: "20000+",
      description: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/cricket/live/czej984w909t",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR2P4y6B1K1PuKhHft4PKYuz4KWirLKueVAf7OL8qvr-xrUEzbnD8LNYbiujbE",
      country: "AE",
      date: "2026-05-28",
      pubTime: "3h ago",
      relatedQueries: [
        "india women vs england women",
        "india women vs england women news",
        "india women vs england women UAE"
      ],
      summary: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights",
      detail: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights\nindia women vs england women is seeing increased search interest in UAE.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  NZ: [
    {
      title: "india women vs england women",
      slug: "nz-india-women-vs-england-women-2026-05-28",
      traffic: "200+",
      description: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/sport/cricket/live/czej984w909t",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR2P4y6B1K1PuKhHft4PKYuz4KWirLKueVAf7OL8qvr-xrUEzbnD8LNYbiujbE",
      country: "NZ",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "india women vs england women",
        "india women vs england women news",
        "india women vs england women New Zealand"
      ],
      summary: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights",
      detail: "England vs India LIVE: First women's T20, Chelmsford - cricket score, radio & highlights\nindia women vs england women is seeing increased search interest in New Zealand.\nSource: BBC.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "sinner",
      slug: "nz-sinner-2026-05-28",
      traffic: "500+",
      description: "Sinner collapses in five-set shock in one of French Open's biggest upsets",
      source: "NZ Herald",
      sourceUrl: "https://www.nzherald.co.nz/sport/tennis/jannik-sinner-suffers-shock-french-open-defeat-to-juan-manuel-cerundolo-after-collapse/J56LXZDJ2BDQXJDVAKJPSKVVXY/",
      imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSUf04EPhBw6AXKiMNs_h0bZr28QGqTsC6SFBZTVwBMh7VkjcZlCvEHixD-ZFw",
      country: "NZ",
      date: "2026-05-28",
      pubTime: "2h ago",
      relatedQueries: [
        "sinner",
        "sinner news",
        "sinner New Zealand"
      ],
      summary: "Sinner collapses in five-set shock in one of French Open's biggest upsets",
      detail: "Sinner collapses in five-set shock in one of French Open's biggest upsets\nsinner is seeing increased search interest in New Zealand.\nSource: NZ Herald.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "blackcaps vs ireland",
      slug: "nz-blackcaps-vs-ireland-2026-05-28",
      traffic: "500+",
      description: "Nathan Smith rips through Ireland as Black Caps test debutant Dean Foxcroft falls short of ton",
      source: "Stuff",
      sourceUrl: "https://www.stuff.co.nz/sport/360985356/nathan-smith-rips-through-ireland-black-caps-test-debutant-dean-foxcroft-falls-short-ton",
      imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQiUOGNi5-zaDi2Ywk3uaSTaZ-lQeU5WQEueKwo1P5E7R1gqeNJgsbfLhuvTcM",
      country: "NZ",
      date: "2026-05-28",
      pubTime: "2h ago",
      relatedQueries: [
        "blackcaps vs ireland",
        "blackcaps vs ireland news",
        "blackcaps vs ireland New Zealand"
      ],
      summary: "Nathan Smith rips through Ireland as Black Caps test debutant Dean Foxcroft falls short of ton",
      detail: "Nathan Smith rips through Ireland as Black Caps test debutant Dean Foxcroft falls short of ton\nblackcaps vs ireland is seeing increased search interest in New Zealand.\nSource: Stuff.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "lynda topp",
      slug: "nz-lynda-topp-2026-05-28",
      traffic: "2000+",
      description: "'What the f***?': Dame Lynda Topp calls out election year Budget in her music awards speech",
      source: "NZ Herald",
      sourceUrl: "https://www.nzherald.co.nz/entertainment/dame-lynda-topp-attends-aotearoa-music-awards-the-first-public-appearance-since-death-of-sister-jools/GSAATNQQ2FDJ5KBN2NFL26X7P4/",
      imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSYqtVhTomNSNsqGPoxDJ_Z-H7aTBq_TmZEPePR0YGPujRuVoeTc8hoFxAiCSU",
      country: "NZ",
      date: "2026-05-28",
      pubTime: "3h ago",
      relatedQueries: [
        "lynda topp",
        "lynda topp news",
        "lynda topp New Zealand"
      ],
      summary: "'What the f***?': Dame Lynda Topp calls out election year Budget in her music awards speech",
      detail: "'What the f***?': Dame Lynda Topp calls out election year Budget in her music awards speech\nlynda topp is seeing increased search interest in New Zealand.\nSource: NZ Herald.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ],
  TW: [
    {
      title: "停電",
      slug: "tw-停電-2026-05-28",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "TW",
      date: "2026-05-28",
      pubTime: "57m ago",
      relatedQueries: [
        "停電",
        "停電 news",
        "停電 Taiwan"
      ],
      summary: "停電 is trending in Taiwan.",
      detail: "停電 is trending in Taiwan.\n停電 is seeing increased search interest in Taiwan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "賭金",
      slug: "tw-賭金-2026-05-28",
      traffic: "100+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "TW",
      date: "2026-05-28",
      pubTime: "1h ago",
      relatedQueries: [
        "賭金",
        "賭金 news",
        "賭金 Taiwan"
      ],
      summary: "賭金 is trending in Taiwan.",
      detail: "賭金 is trending in Taiwan.\n賭金 is seeing increased search interest in Taiwan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    },
    {
      title: "楊洋",
      slug: "tw-楊洋-2026-05-28",
      traffic: "200+",
      description: "",
      source: "",
      sourceUrl: "",
      imageUrl: "",
      country: "TW",
      date: "2026-05-28",
      pubTime: "2h ago",
      relatedQueries: [
        "楊洋",
        "楊洋 news",
        "楊洋 Taiwan"
      ],
      summary: "楊洋 is trending in Taiwan.",
      detail: "楊洋 is trending in Taiwan.\n楊洋 is seeing increased search interest in Taiwan.\nSearch interest is moving quickly as people look for current updates.\nIssueGlobe is tracking this topic through Google Trends RSS data.\nCheck back as the ranking can change throughout the day.",
      reactions: "People are searching for updates, background, and related coverage as this topic gains momentum."
    }
  ]
};

export function getPreloadedTrends(countryCode: string): TrendItem[] {
  return preloadedTrends[countryCode] || [];
}
